### ISSUE TITLE
Log do Sat

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#10]
Boa tarde,

Existe alguma forma "simples" de gravar o log (informar o nome do arquivo) ou somente usando o NLog que usou?
Hoje migrei o primeiro cliente em produção do ACBrSat para o ACBr.Net.Sat e tive que usar algumas vezes o ExtrairLog para pegar algumas falhas.

Só para constar, obtive sucesso, já estou usando o ACBr.Net.Sat em produção.

Abraços

**Comment by rftd** [comment]
Não ou usa o NLog ou o log4net ou implementa as Intefaces de Log que estão na ACBr.Net.Core.
Não vejo necessidade de usar log customizado com tantas bibliotecas fazendo o mesmas coisa.

**Comment by marcosgerene** [comment]
Boa tarde,

OK, vou ver o que acho melhor, se eu implementar algo dou um pull request e a gente analisa juntos.

Hoje meu cliente disse que um dos cupons que ele cancelou, ao imprimir (e também ao tentar reimprimir) dava problema, me mandou uma foto, aonde fica o QRCode em determinado ponto imprimia caracteres estranhos ao invés do QRCode e travava a impressora.

Isto aconteceu apenas com um cupom, vou tentar pegar o XML para dar uma olhada e entender o que ocorre, não sei dizer se é no cancelamento ou no cupom ainda (quando cancelo imprimo o cancelamento e reimprimo o cupom original).

Não sei dizer nem se o problema está no ACBr.Net ou no ACBr, pois se o cupom foi emitido normalmente acho que o problema está na impressão, mas com o ACBr no Lazarus rodo a 6 meses e nunca aconteceu nada semelhante.

Obs: Para impressão uso o ACBr via Lazarus, passo apenas um caminho do XML e mando imprimir.
Obs2: A impresora é uma Elgin i9
Obs3: Emiti e cancelei um cupom logo em seguida e funcionou perfeitamente.
Obs4: O Sat é da Elgin.

**Comment by rftd** [comment]
@marcosgerene Você pode usar um custom no seu projeto e setar ele para ser usado pelo ACBrSat, mas é só isso nada vai ser adicionado ao projeto em relação a isso.

`LoggerProvider.SetLoggerFactory<MyLogFactory>();`

Você precisa implementar as interfaces ILogFactory, IACBrLogger na sua aplicação.
