### ISSUE TITLE
Falha Emissão

### ISSUE THREAD

**Issue by AlanJovita** [ACBrNet/ACBr.Net.Sat#100]
Boa tarde, estou tentando emitir um cupom em um cliente e estou tendo o seguinte erro:

_System.AccessViolationException: Tentativa de leitura ou gravação em memória protegida. Normalmente, isso é uma indicação de que outra memória está danificada.
   em ACBr.Net.Sat.SatStdCall.<>c__DisplayClass14_0.<EnviarDadosVenda>b__0()
   em ACBr.Net.Core.InteropServices.ACBrSafeHandle.ExecuteMethod[T](Func`1 method)_

Já dei a permissão do windows para as pastas onde contem as Dlls do SAT e sem sucesso.
Alguem pode me dar uma luz ? 

**config:
Windows 8
SAT Elgin Linker I**

Grato desde já

**Comment by marcosgerene** [comment]
@AlanJovita 

Sei que parece meio bobo, mas o seu software perde permissão de admin para rodar? tentou rodar como admin?

Outra coisa do elgin Linker I é uma dll chamada zlib ou zlib1, tenta colocar ela na mesma pasta do seu executável e executa ele como admin... geralmente funciona, devo ter meia duzia de clientes usando a biblioteca com o Linker I.

PS: a dll que falei você  encontra na pasta de instalação do Linker Manager

**Comment by AlanJovita** [comment]
@marcosgerene 

Perfeito amigo, era isso mesmo! fiz a copia das dlls zlib e zlib1 para a pasta do sistema e tambem system32 e sysWow64, problema resolvido!

Muito Obrigado pela ajuda :)
