### ISSUE TITLE
Conversão XML to CFe

### ISSUE THREAD

**Issue by HimorriveL** [ACBrNet/ACBr.Net.Sat#101]
é possível fazer a conversão de XML para CFe? na classe tem " var dadosVenda = cfe.GetXml(options);" porém não achei o contrario, podem me confirmar por favor?

**Comment by rftd** [comment]
O método load é estático.
var cfe = CFe.Load("cfe,xml");

**Comment by rftd** [comment]
Se olha no demo no menu venda tem a opção de carregar o xml

**Comment by HimorriveL** [comment]
perfeito pessoal, obrigado pelos esclarecimentos
