### ISSUE TITLE
Mensagem de Retorno

### ISSUE THREAD

**Issue by HimorriveL** [ACBrNet/ACBr.Net.Sat#102]
Dentro do SAT existe a string MensagemRetorno. Fiz um teste para dar erro, e ao dar erro 7099 (tentativa de cancelamento acima de 30 min) verifiquei que o retorno dele está vazio, a DLL tem a função de dar essa informação? ou realmente vou ter que pegar o código e fazer um mapeamento para devolver a informação amigável ao usuário?

**Comment by marcosgerene** [comment]
@HimorriveL 

Quem devolve o ID e string da mensagem é a dll da fabricante em base64.

A biblioteca (ACBR) transforma esse base64 em xml, salva na pasta e faz a serealização dele.

Se está vindo sem mensagem, provavelmente é porque a dll do fabricante não está enviando.
