### ISSUE TITLE
Desabilitar Assinatura de Driver

### ISSUE THREAD

**Issue by adrbarros** [ACBrNet/ACBr.Net.Sat#103]
Boa tarde, alguem com problemas no Windows 10? Toda vez que o Windows tem algum Update, o SAT para de funcionar. Assim, toda vez tem que ser feito a Desativação da Solicitação de Assinatura de Driver
Esse processo aqui:
https://answers.microsoft.com/pt-br/edge/forum/all/desabilitar-imposi%C3%A7%C3%A3o-de-assinatura-de/6dc89de3-8998-429d-86fd-c6c6fc984ae0

Alguma solução, ou vocês não passam por isso?

**Comment by marcosgerene** [comment]
@adrbarros 
Eu tenho o mesmo problema.
No elgin, o driver novo (do Smart) funciona para todas as versões (LInker 1, 2  e o smart) e aparentemente resolve o problema.

Nos outros modelos, ainda não consegui notar.

**Comment by adrbarros** [comment]
@marcosgerene 
Rapaz, Elgin até parei de indicar.
Mas agora estou com o mesmo problema no Epson/Gertec que são os mesmo, no Tanca e no Bematech, pois o cliente atualizou 22 pdvs para o Win 10
O Restante (Urano, Sweda, ControlID, Nitere, Daruma, Dimep) estão com Windows 7 sem dor de cabeça

**Comment by rftd** [comment]
Então isso são os fabricantes deviam validar o seus drivers com a M$ sendo que no windows 10 a coisa é um pouco diferente da do windows 7

**Comment by adrbarros** [comment]
Grato a todos
