### ISSUE TITLE
Testar com o DEMO ?

### ISSUE THREAD

**Issue by marcosmarchiore** [ACBrNet/ACBr.Net.Sat#104]
Olá, estou tendo dificuldades para fazer o teste com o demo do .net.sat, alguém pode me dar uma luz, já baixei o emulador de SAT do site da receita de São Paulo e já compilei aqui o demo também, só não consigo fazer o mesmo funcionar com os testes.
Vlw.

**Comment by marcosgerene** [comment]
@marcosmarchiore .

Bom dia cara, tudo bem?

Sua duvida/problema está um pouco vaga de mais... pode me dizer o que você já fez, qual o erro/problema que está enfrentando, postar um trecho de código, sei la.. ?

Vou postar aqui um XML de um SAT de emulador, meu emulador esta funcionando normal aqui, versão 2.9.4.

[CFe35200911111111111111591234567890001068653511.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/5245304/CFe35200911111111111111591234567890001068653511.zip)

**Comment by rftd** [comment]
Fechando issue por falta de retorno do usuário.
