### ISSUE TITLE
Emissão apenas do CFe sem o módulo

### ISSUE THREAD

**Issue by nielson266** [ACBrNet/ACBr.Net.Sat#105]
Boa Noite Pessoal!
Aqui no Ceará existe uma lei que permite contribuintes emitir CFe sem o módulo, como posso fazer isso utilizando o acbr visto que ele verifica se está ativo o mfe?

Obrigado! Excelente trabalho!!!!

**Comment by rftd** [comment]
Sem o modulo fiscal é impossível emitir CFe, no caso esta lei deva falar da NFCe e este componente não implementa isso..
