### ISSUE TITLE
Ajuda com implementação do sat

### ISSUE THREAD

**Issue by brunosouza25** [ACBrNet/ACBr.Net.Sat#106]
bom, eu estou fazendo um projeto para a faculdade e não estou conseguindo a integração do sat no meu sistema de PDV, não sei se isso é uma coisa que vcs poderiam me ajudar, eu não quero copiar nada, só queria aprender a fazer isso, meu professor pediu para mim fazer meu sistema validar só alguns parâmetros com aquele programa da Sefaz em JAVA

**Comment by marcosgerene** [comment]
@brunosouza25 

Baixa o emulador na versão 2.9.4.

Tem um manual de como configurar, mas vou mandar a minha pasta dele e as minhas configs para facilitar sua vida.

Só jogar essa pasta no C: 
[SAT.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/5710797/SAT.zip)

C:\Sat\
![image](https://user-images.githubusercontent.com/15945003/102515095-12251d80-406c-11eb-900b-bf2e0709d3df.png)


Você vai apontar o emular para a dll C:\Sat\sat.dll

Use o demo deste projeto para entender como ele funciona e configure conforme abaixo:

Modelo: CdCel (para o emulador)


Sign AC: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

SW: 26363645000182 (meu cnpj)

Ativação: 12345678

Emitente
Cnpj: 11111111111111
IE: 111111111111


![image](https://user-images.githubusercontent.com/15945003/102514740-9a56f300-406b-11eb-91ff-3f84f4361662.png)


XML de exemplo:
[CFe35200911111111111111591234567890001129532328.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/5710781/CFe35200911111111111111591234567890001129532328.zip)

**Comment by rftd** [comment]
Fechando issue por falta de retorno do usuário.
