### ISSUE TITLE
Problemas SAT com o Windows forms C# CORE

### ISSUE THREAD

**Issue by khaddmussistemas** [ACBrNet/ACBr.Net.Sat#107]
Boa noite,
Tudo bem? 

Estou migrando meu sistema de windows forms .NET para windows forms .CORE c# . 
E quando vou usar o metodo Consultar SAT da dll mfe.dll dá um erro:
"Foi feita uma tentativa de se carregar um programa com um formato incorreto. (0x8007000B)"
Alguem poderia me dar uma força?
Grato!

**Comment by leandrovip** [comment]
Boa noite.
Ta usando qual método pra chamar a dll, stdcall ou cdecl? Tentou alterar?
Esta compilando para x86 ou x64?

**Comment by khaddmussistemas** [comment]
Estou usando any cpu.
windows forms core net core 3.1 .
Funciona no windows forms .NET 4.7.
Mas como estou migrando meu sistema estou apanhando com isso.
é nesse consultar SAT.

[image: image.png]
Dá esse erro.
Foi feita uma tentativa de se carregar um programa com um formato
incorreto. (0x8007000B)

Em qui., 7 de jan. de 2021 às 21:38, Leandro Ferreira <
notifications@github.com> escreveu:

**Comment by rftd** [comment]
Pelo erro parece que ta tentando carregar uma dll x86 em um programa x64 ou vice versa.
Outra coisa onde ocorre este erro ?
Manda o stacktrace ou um tutorial de como simular o erro usando o demo do projeto.

**Comment by rftd** [comment]
Fechando issue por falta de resposta do usuário.
