### ISSUE TITLE
Dependência do projeto ACBr.Net.DFe.Core incorreta

### ISSUE THREAD

**Issue by eliezeralmeida** [ACBrNet/ACBr.Net.Sat#108]
Imagem do problema ocorrido:
![image](https://user-images.githubusercontent.com/2786448/105220238-345ffe80-5b36-11eb-9325-3cf1c2e4835e.png)

Para resolver o problema no projeto tive que voltar a versão dos projetos ACBr.Net.DFe.Core e consequentemente voltou também do projeto Integrador.

Pelo que entendi a ultima versão do projeto ACBr.Net.Sat está com uma dependência fixada na versão 1.2.7.1 do projeto ACBr.Net.DFe.Core.

Segue imagem de como tive que deixar as versões no meu projeto para resolver o problema:
![image](https://user-images.githubusercontent.com/2786448/105220511-97519580-5b36-11eb-9627-5bd3ebca102a.png)

Não consegui comparar a versão 1.2.7.1 com a 1.2.8 do projeto ACBr.Net.Dfe.Core para ver se houve alguma alteração importante. Porém para resolver o problema deixei a versão 1.2.7.1 em produção.

**Comment by rftd** [comment]
Não consegui reproduzir este erro não

**Comment by eliezeralmeida** [comment]
> Não consegui reproduzir este erro não

Tem que colocar todos os pacotes na ultima versão existente.
No caso o ACBr.Net.DFe.Core da conflito quando está na versão v1.2.8 e o Sat na versão 1.2.7.1.

O erro ocorre ao utilizar o pacote ACBr em alguma tela ou classe.

**Comment by rftd** [comment]
Cara nem tem problema nenhum, favor passar um passo a passo de como fazer este bug usando o demo.

**Comment by adrbarros** [comment]
Pull Request #109 corrige esse erro na complilação do projeto
