### ISSUE TITLE
[RemoverAcentos] Valores sem o ponto (separador decimal)

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#11]
O problema do valor continua ao usar a propriedade RemoverAcentos, notei no ACBr.Net.Core que você fez algo para corrigir, atualizei minhas DLLs (peguei as que estão na pasta Lib) do ACBr.Net.Sat mas não obtive sucesso.

Devo baixar o ACBr.Net.Core e compilar? Como funciona quando preciso das DLLs do ACBr.Net? Devo sempre pegar da pasta Lib?

PS: Acabei de ver que atualizou as Libs, dei update, recompilei o ACBr.Net.Sat com as novas libs, joguei as 3 DLLs novas, mas não deu certo

**Comment by rftd** [comment]
estranho pois agora ele só substitui os caracteres, vou ver o que pode estar acontecendo.
