### ISSUE TITLE
Erro na Conversão de Data (ConsultaStatusOperacional) em um Equipamento Novo

### ISSUE THREAD

**Issue by adrbarros** [ACBrNet/ACBr.Net.Sat#111]
Ao realizar a consulta do Status Operacional no SAT/MFE, 
o Horario da Ultima Transmição é listada da seguinte forma: 00/00/0000 - 00:00:00,
assim, no retorno da string = 00000000000000, gerando erro na conversão da Data

![image](https://user-images.githubusercontent.com/15065213/120076702-56860200-c07d-11eb-98ad-489ddf32dade.png)

Erro nesse ponto:
![image](https://user-images.githubusercontent.com/15065213/120076953-64885280-c07e-11eb-9701-1b7b87c2fd0f.png)

para testar aqui passar na conversão, coloquei dessa forma:
![image](https://user-images.githubusercontent.com/15065213/120077028-b4ffb000-c07e-11eb-8513-eef101ccc312.png)

**Comment by rftd** [comment]
Traduzindo fabricante fazendo merda como sempre
Tente assim por favor
Status.DhCFe = DateTime.TryParseExact(RetornoLst[i], "yyyyMMddHHmmss", CultureInfo.InvariantCulture, DateTimeStyles.None, out var data) ? data : DateTime.MinValue;
