### ISSUE TITLE
Impressão do cupom

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#14]
Boa tarde @rftd ,

O que você está usando hoje para impressão? Eu tinha um programinha em Lazarus que eu chamava para emitir o cupom todo, agora que migrei para o Acbr.Net.Sat estou usando ele somente para imprimir.

Queria remover ele de vez do projeto, mas não achei nada em .Net para imprimir o cupom... você usa o que?

**Comment by leandrossantos** [comment]
@marcosgerene sobre a impressão, como você chama esse programinha que você fez, tem como disponibilizar ele enquanto não tem a impressão nativa na DLL ??

**Comment by marcosgerene** [comment]
@leandrossantos vou ver se consigo ainda essa semana converter ele em DLL, ainda preciso pensar como vou fazer com o logo, pois tirando ele todo o resto é lido do xml... assim que tiver novidades posto aqui, abraço

**Comment by leandrossantos** [comment]
@marcosgerene pega a ideia do adenilton da Zeus.Net.NFe.NFCe

**Comment by marcosgerene** [comment]
Boa tarde @leandrossantos.

Tive que praticamente começar do zero o que eu tinha, mas foi bom, acho que vou usar desta forma agora ao invés de mandar mais um executável pro cliente, pretendo implementar a Danfe da NFe em breve também.

Vou te mandar o fonte (em Lazarus) e a dll em, eu testei somente o que está no projeto de teste do c# e funcionou. Se tiver algum problema com ela me manda  um e-mail mgf.spirito@gmail.com.

Vou postar ele no projeto do Acbr para ver se o pessoal pode me dar algumas dicas de como melhorar isto, é a primeira dll que eu crio.

Link: https://drive.google.com/file/d/0B2BaoP4yRQxhNnd0a2prM3h4dlk/view?usp=sharing

**Comment by rftd** [comment]
Implementado impressão do Extrato em FastReports

https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport
