### ISSUE TITLE
[URGENTE] Inconsistência no schemas

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#16]
Estou usando um SAT, a versão é 0,07, e todo envio da erro de inconsistencia no schemas no atributo ide, não sei mais o que fazer... pode me dar uma luz?

**Comment by rftd** [comment]
Qual o SAT você esta usando pois acabei de fazer testes no Emulador usando o Layout 0.07 e funcionou corretamente.
Se possivel me passa um passo a passo como reproduzir o erro usando o emulador da SEFAZ e o demo do ACBrSat

**Comment by marcosgerene** [comment]
o LINKER Elgin,

Acabei de fazer um teste, a tag tpAmb não deve ser informada e está sendo...

**Comment by marcosgerene** [comment]
Tentei jogar a propriedade como não obrigatória, mas a função cfeAtual.GetXml() da erro...

**Comment by rftd** [comment]
Na verdade teria que colocar como nullable e setar naoobrigatoria, eu já to corrigindo aqui assim que possível envio

**Comment by marcosgerene** [comment]
Ok, aguardo seu retorno... tem noção de tempo? porque vou aproveitar para instalar outro sat enquanto isso...

**Comment by rftd** [comment]
cara eu to no serviço no momento devo mecher na hora do almoço com isto.

**Comment by rftd** [comment]
Correção enviada.

**Comment by marcosgerene** [comment]
A impressão vai funcionar normal tbm?

**Comment by rftd** [comment]
Acabei de enviar uma correção para impressão.

**Comment by marcosgerene** [comment]
@rftd Deu tudo certo, este cliente é SN, assim que aparecer uma oportunidade testo em Regime Normal...

abraço
