### ISSUE TITLE
Troco errado

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#17]
Boa noite,

Estou fazendo alguns testes como desconto, e em um cupom o troco foi calculado errado.

Entretanto o componente não envia o troco, somente o xml de retono. Seria um bug do emulador?

[troco.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/640651/troco.zip)

**Comment by rftd** [comment]
Então os cálculos são feito pelo SAT então pode sim ser erro do emulador.

**Comment by marcosgerene** [comment]
@rftd ,

Olhando o xml de envio não consigo encontrar qualquer inconsitência, vou relevar o erro por nunca ter acontecido em produção
