### ISSUE TITLE
Inconsistência no schemas XML (elemento: prod)

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#18]
Bom dia @rftd ,

Estou com um problema ao emitir o SAT depois que atualizei meu sistema (não houve mudanças no componente).

Extraindo o log recebi: **Inconsistência no schemas XML (elemento: prod).**

Atualizei o SAT da versão 0.06 para 0.07, mas não obtive sucesso.

**Comment by marcosgerene** [comment]
Acho que achei o problema, a tag vProd não deve existir.

Abraço

**Comment by marcosgerene** [comment]
Boa tarde, o problema era meu, eu não deveria informar a tag vProd, parei de informar e voltou ao normal.

Obrigado, abraço

**Comment by rftd** [comment]
Sim este campo é de calculo do SAT ele que preenche você informa o qProd e o vUnCom e ele faz o calculo, lembrando que em caso de valores fracionados você precisa informar se o sat vai arredondar ou truncar o valor na tag indRegra.
