### ISSUE TITLE
[Dúvida] No SAT Preciso ativar conexão e desativar toda vez?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#19]
No sat preciso ativar conexão e desativar toda vez? 

To perguntando porque nunca mexi com SAT ai queria saber se posso ativar e desativar a conexão ou 
se é recomendavel deixar ativada a conexão 

Aqui temos um emissor de NFc-e, e oque acontece pretendo somente alterar o método Finalizar meu para finalizar com SAT ou NFc-e (o cliente escolheria na primeira configuração do sistema oque usa)

**Comment by rftd** [comment]
o Ativar conexão do sat carrega a biblioteca sat para poder ser usada, eu uso ativando e desativando conforme vou usando.

**Comment by robertorp** [comment]
Hm, então acha que daria certo oque disse? Quando eu for finalizar o cupom eu ativo ele, faço tudo, desativo.

Não teria grandes percas de performance no caso

**Comment by rftd** [comment]
Não pois o ativar é basicamente executa uma função do windows para pegar o handler da biblioteca e usar ele para fazer as chamadas.
Eu uso desta maneira mesmo no finalizar preencho o cfe, ativo, envio faço todos os processamentos necessário e no fim desativo.

**Comment by robertorp** [comment]
@rftd muito obrigado! queria saber somente isso mesmo hehe
