### ISSUE TITLE
Tag CPF

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#20]
Boa tarde,

O sistema de um cliente meu não esta importando o arquivo do sat sem o destinatário e sem a tag cpf, tem como ao invés de ocultar a tag sat sair assim 

<  CPF   /    >

(sem os espaços, so coloquei se não o github oculta

**Comment by rftd** [comment]
Não tem como pois segundo o schema deve ter só 1 dos dois, pode haver SAT que não valide o xml por causa disso.

**Comment by marcosgerene** [comment]
Não quero o cnpj, somente o cpf quando não tiver nenhum, mas ao invez de ocultar aparecer assim...

**Comment by marcosgerene** [comment]
Não quero o cnpj, somente o cpf quando não tiver nenhum, mas ao invez de ocultar aparecer assim... ex:
```
<dest>
   <xNome>CONSUMIDOR</xNome>
   <CPF/>
</dest>
```

**Comment by rftd** [comment]
Eu to vendo na especificações do SAT e  a ocorrência é 0 - 1 ou seja se tiver vazio não aparecer.

**Comment by marcosgerene** [comment]
@rftd ,

Fiz diferente, quando o cara não informar CPF ou CNPJ eu simplesmente vou ignorar o fato de ter informado ou não o nome, assim ele vai gerar a tag *dest* em assim:

```
<dest/>
```
