### ISSUE TITLE
[Comunicação]

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#21]
Boa tarde @rftd,

O "problema" abaixo ocorre em um cliente meu que usa um notebook (relativamente velho, mas está rodando bem um windows 7 SP1 x64) com um SAT da Elgin, o Linker SAT I (aquele que é praticamente igual ao Dimep).

No começo do dia, ao ligar o computador e plugar o SAT o cliente consegue emitir os cupons de forma tranquila, porém, ele liga o computador de manhã e só emite os cupons no final do dia, por volta das 18horas e ao emitir não consegue por falha na comunicação.

Depois de vários testes, o meu chute mais lógico seria que o notebook "desliga" a USB (no PC dele o SAT só funciona se está conectado a uma única USB) após um tempo para economizar a energia e hoje mudei para alto desempenho para fazer um teste, ainda não obtive a resposta.

Bem tudo que disse antes, nada é feito via componente, é tudo hardware, logo não tem nada a ver com o PC, entretanto, notei algumas coisas interessantes, se eu removo o SAT da USB, espero desligar e religo, ele continua com este problema, só volta ao normal se reiniciar o PC, mas aqui temos o real motivo desta insue, se ao invés de eu desligar o PC eu abrir o Linker Manager (software da Elgin) e logar na opção ativado somente para ver o status do aparelho e fechar o Linker Manager tudo volta a funcionar "num passe de mágica".

A pergunta: como eu poderia fazer via componente o mesmo que o Linker Manager faz hoje para "resgatar" essa comunicação?

**Comment by rftd** [comment]
A comunicação é toda feita pela Dll do fabricante se o mesmo colocou algo que não tem nas especificações técnicas do SAT não tenho o que fazer.

**Comment by marcosgerene** [comment]
@rftd,

A minha questão é saber se existe algo que "force" essa comunicação, meu fluxo hoje basicamente é

Ativa()
Vende()
Desativa()

**Comment by rftd** [comment]
não tem nenhuma chamada que force a comunicação pois tudo é tratado pela dll do fabricante o ACBrSat só faz chamadas do métodos, todos os métodos do ACBrSat são os métodos que tem que ter na dll do fabricante.

**Comment by marcosgerene** [comment]
Então vou ter que pensar em alguma outra forma de contornar isto.

Obrigado, abraços
