### ISSUE TITLE
Entender o funcionamento da lib/ como funciona o SAT para nos desenvolvedores

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#23]
Como funciona a dll aqui?

Ela comunica com outras dll enviando o comando correto?
Através disso presumo que os comandos de todas DLL sat tem um comando de "Enviar" padrão
"Cancelar" padrão etc.. (correto?)

Logo então esse é o motivo de fazer load na DLL ... certo?

Existe algum documento no qual eu posso estar estudando mais o SAT? Digo desde a parte em que eu adquirir um sat quais os procedimentos tomar?

Quando foi configurar pelo sistema de automação comercial (AC) 
Exemplo

No app teste daqui tenho o menu "Ativação"
eai? oque seria esse menu porque ele? Digo quero entender oque eu tenho que fazer no software para ativar o sat , vincular a assinatura é.. Quais passo devem ser tomados (passo por passo) 

Estou no software AC primeira inicialização

1- Estou com o código de ativação em posse na minha mão.. (ou preciso ligar para algum lugar para obter ele?)
2- Tenho que comunicar o certificado no AC também? igual um nfc-e/nf-e qualquer 
3- Associar assinatura, (essa assinatura é da software house ou seja.. e da empresa que desenvolve o AC?) logo então isso é um processo interno meu.. poderia adicionar isso no meu AC internamente sem necessidade de nada.. de intervenção nem uma. Onde adquiro a assinatura?)
4- Trocar código de ativação, realmente ele troca o código simples assim? quando quiser? 
5- Bloquear e desbloquear (Qual a utilidade disso para o cliente?)
6- Atualizar SAT (o AC envia o comando e o SAT sera atualizado? correto? soh isso? simples assim rsrs?)
7- ler/gravar/configurar xml de interface de rede? isso seria em teoria uma porta na rede que fica monitorando no qual o sat fica esperando xmls chegar e envia xmls de resposta? no app teste clico em configurar interface de rede e nada acontece.
8- Pagina de código isso serve para que?(No app teste, do lado de utf8)
9- Inicializar ele inicializa oque exatamente? Digo precisa de deixar algo aberto no sat? ou ele simplesmente pega uma referencia.

**Comment by marcosgerene** [comment]
Boa noite @robertorp ,

**Sobre a DLL:**
Cada fabricante fornece sua própria DLL, logo a Elgin vai ter uma DLL, a Gertec outra, a Epson outra e o Emulador do sat outra, entretanto todas devem seguir exatamente o mesmo padrão, o que faz com que o componente funcione de forma identica na DLL de qualquer fabricante.

**Documento para estudar:**
Nunca achei um manual do SAT, eu simplesmente estudei os Demos (antes daqui usava o ACBr em lazarus) e implementei.

**Vincular e ativar:**
Quando o contribuinte adquire o aparelho ele não está "linkado" à empresa na Sefaz (isso vai ser importante na assinatura) e está inativo, o processo de vincular basicamente é logar como contribuinte no SGRSAT (https://satsp.fazenda.sp.gov.br/COMSAT/Account/LoginSSL.aspx?ReturnUrl=%2fCOMSAT) e dizer que aquele número de série pertente ao contribuinte.

Quanto ao processo de ativação (que deve ser feito após vincular), você define a senha no ato da ativação, essa senha é importante, não a perca (o pessoal aqui usa senhas como 12345678).

**Agora o mini-enem** rs:

_1- Estou com o código de ativação em posse na minha mão.. (ou preciso ligar para algum lugar para obter ele?)_
Já respondi acima, vc define o código no ato da ativação.

_2- Tenho que comunicar o certificado no AC também? igual um nfc-e/nf-e qualquer_
Não, você deve gerar uma assinatura de 344 caracteres através do certificado de uma empresa credenciada como SOFTWARE HOUSE (para terceiros ou uso próprio), para tal existe o Acbrsign ou se quiser te mando uma rotina que tenho aqui.
No ato vinculação do SAT vc pode escolher se aceita o certificado do aparelho como válido (1ª opção, padrão e extremamente aconselhável), neste caso o próprio aparelho se encarrega de assinar e enviar os documentos.

_3- Associar assinatura, (essa assinatura é da software house ou seja.. e da empresa que desenvolve o AC?) logo então isso é um processo interno meu.. poderia adicionar isso no meu AC internamente sem necessidade de nada.. de intervenção nem uma. Onde adquiro a assinatura?)_
A assinatura é gerada através da string gerada pela concatenação do seu CNPJ (no caso, desenvolvedor) e o CNPJ do contribuinte, mas tem jeito de automatizar isso, já faço isso no meu sistema.

_4- Trocar código de ativação, realmente ele troca o código simples assim? quando quiser?_
Vou deixar essa pro @rftd.

_5- Bloquear e desbloquear (Qual a utilidade disso para o cliente?)_
Vou deixar essa pro @rftd.

_6- Atualizar SAT (o AC envia o comando e o SAT sera atualizado? correto? soh isso? simples assim rsrs?)_
Sim

_7- ler/gravar/configurar xml de interface de rede? isso seria em teoria uma porta na rede que fica monitorando no qual o sat fica esperando xmls chegar e envia xmls de resposta? no app teste clico em configurar interface de rede e nada acontece._
O SAT tem comunicação direta com a internet para que ele possa enviar os arquivos para a SEFAZ (como eu havia te explicado anteriormente via wpp), pois o AC somente manda o arquivo ao aparelho, que se comunica com a SEFAZ é o aparelho.

_8- Pagina de código isso serve para que?(No app teste, do lado de utf8)_
@rftd 

_9- Inicializar ele inicializa oque exatamente? Digo precisa de deixar algo aberto no sat? ou ele simplesmente pega uma referencia._
O inicializar carrega a DLL para uso, se manter inicializado precisaria fechar seu software para que outra ferramenta (como um Linker Manager da vida) acessasse o aparelho para outros fins. Eu aconselho fazer assim:
Inicializar()
Vender() //Ou outra coisa qualquer
Desinicializar()


Espero ter elucidado pelo menos alguma coisa rs

Abraços

**Comment by robertorp** [comment]
2- _No ato vinculação do SAT vc pode escolher se aceita o certificado do aparelho como válido (1ª opção, padrão e extremamente aconselhável), neste caso o próprio aparelho se encarrega de assinar e enviar os documentos._
O aparelho internamente tem certificado? Ou é um certificado que vem acompanhado do aparelho .cer pelo que vi no app teste?

3- Surgiu uma outra duvida, deve ser o cnpj da empresa desenvolvedora? Digo no nosso caso trabalhamos com revendas, logo então cada revenda tem um cnpj também poderia ser as das revendas? Até porque são elas que dão suporte nos clientes, afinal os clientes são das revendas(Nós damos suporte quando a revenda entra em contato, logicamente a revenda entra em contato em casos mais extremos). 
[Outra aqui no 3] 
Se entendi bem eu tenho opções, uso um certificado ou uma chave de 344 dígitos(Ambos para assinar). Correto?

**Comment by rftd** [comment]
**Documentos do SAT se encontram nesta URL**

http://www.fazenda.sp.gov.br/sat/downloads/vigentes.asp

**Perguntas**

2 - Sim o aparelho tem certificado internamente ele que trata de assinar o XML so precisa informar o Certificado se você optar por usa um e-CNPJ seu em vez de usar o certificado fornecido pela SEFAZ/SP

3- Não você não tem estas duas opções a unica opção é gerar a assinatura tem o metodo no ACBrSAT de como gerar, a unica coisa que você escolhe é usar o certificado fornecido pela SEFAZ ou um e-CNPJ seu, e-CNPJ não é o certificado usado na NFe.

4- Sim você troca o código de ativação simples assim.

5- Basicamente isto é para quando vai enviar o SAT para outro local e não quer correr risco de alguém usar mas na pratica nenhum.

8- Pagina de código é usado para comunicar com o SAT, pode ser que o SAT não trabalhe com UTF8 e com isto não reconheças os caracteres acentuados.

**Comment by robertorp** [comment]
Sobre portas COM essas coisas não existem no SAT? Somente mando o ativar ele vai achar automaticamente?

**Comment by rftd** [comment]
Sim no SAT não tem porta COM nada você precisa apenas setar o caminho da biblioteca SAT e o tipo de convenção, cecdl ou stdcall.
O Inicializar so carrega a lib para uso no ACBrSat

**Comment by rftd** [comment]
Vou fechar a issue caso tenha mais duvida reabra a mesma.
