### ISSUE TITLE
Gerar chave de associação 

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#24]
Bom oque quero saber é posso gerar essa chave com qual certificado digital? 
Cliente?
Desenvolvedora?
Revenda?

Enfim qual certificado é usado?

Fiz esse código ele funciona perfeito com certificado A1 já com A3 ou quando você obtem do repositório do windows , da erro na exportação da private key (Pelo que li se não tiver essa exportação o .net não tem suporte para SHA2 que no caso temos SHA256 incluida nessa)

`var certificado = new X509Certificate2(@"C:\Users\Roberto\Desktop\certifi\certificado.pfx",
                "senha", X509KeyStorageFlags.Exportable);

                var privateKeyProvider = (RSACryptoServiceProvider)certificado.PrivateKey;

                var cnpjs = "2102576000012321025760000123";

                var data = Encoding.UTF8.GetBytes(cnpjs);

                Console.WriteLine("Data : " + BitConverter.ToString(data));

                RSACryptoServiceProvider privateKey1 = new RSACryptoServiceProvider();
                privateKey1.ImportParameters(privateKeyProvider.ExportParameters(true));

                var sig = privateKey1.SignData(data, "SHA256");

                Console.WriteLine("Signature: " + BitConverter.ToString(sig));

                var chaveBase64 = Convert.ToBase64String(sig);

                Console.WriteLine("chave: " + chaveBase64);
                Console.WriteLine("Tamanho: " + chaveBase64.Length);

                bool verified = privateKey1.VerifyData(data, "SHA256", sig);`

este código funciona perfeito para gerar a chave de associação com certificado digital A1.
A3 não funciona.
Ai e onde queria dicas de alguém que já fez .

esse exemplo ai fiz olhando o da sefaz de sp segue o link.
http://www.fazenda.sp.gov.br/sat/downloads/Assinador%20Certificado%20Tipo%20A3.txt

Aqui temos alguns posts sobre o assunto
https://blogs.msdn.microsoft.com/alejacma/2010/06/02/an-internal-error-ocurred-when-using-sha-2-algorithms-with-signedcms/

https://blogs.msdn.microsoft.com/shawnfa/2008/08/25/using-rsacryptoserviceprovider-for-rsa-sha256-signatures/

http://stackoverflow.com/questions/10673146/signature-with-sha256

**Comment by robertorp** [comment]
Aparentemente funcionou extraindo o certificado digital do repositorio do windows com esse código aqui

`var certificado = ListareObterDoRepositorio();
                

                var privateKeyProvider = certificado.GetRSAPrivateKey();

                var cnpjs = "2102576000012321025760000123";

                var data = Encoding.UTF8.GetBytes(cnpjs);

                Console.WriteLine("Data : " + BitConverter.ToString(data));


                //RSACryptoServiceProvider privateKey1 = new RSACryptoServiceProvider();
                //privateKey1.ImportParameters(privateKeyProvider.ExportParameters(true));

                var sig = privateKeyProvider.SignData(data, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

                Console.WriteLine("Signature: " + BitConverter.ToString(sig));

                var chaveBase64 = Convert.ToBase64String(sig);

                Console.WriteLine("chave: " + chaveBase64);
                Console.WriteLine("Tamanho: " + chaveBase64.Length);`

lembrando que usei o .net 4.6.2 para esse aqui. Na abertura da issue foi usado o 4.5

Gerou igual o do ACBrSatSign

Fazendo mais testes aqui. 
Lembro que esse código e somente teste por isso não usei os métodos dispose rsrs (no 4.6 temos eles para a classe RSA , X509 bom e deve ter em muitas outras por ai)

Agora vou pesquisar sobre o terceiro parâmetro RSASignaturePadding.Pkcs1. Para verificar se isso não pode gerar algo estranho hehe.

edit: Pkcs1 para autopreenchimento é o padrão/unica opção do .net 4.5
edit2: Fiz vários testes e gerou sempre igual o do acbr

Vou fazer uma abstração disso melhor e postarei zipado aqui para caso alguém mais precise.
Lembrando que, vou usar .net 4.6+

**Comment by robertorp** [comment]
Ta ae, se alguém passar por algo do tipo, uma alternativa de solução.
edit: .net 4.6+
[GerarAssinaturaDeAssociacao.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/777488/GerarAssinaturaDeAssociacao.zip)

**Comment by rftd** [comment]
Você chego a testar o metodo GerarSignAc do ACBrSat

**Comment by robertorp** [comment]
Tem? Não sabia. hehe

**Comment by rftd** [comment]
não lembro se enviei para o nuget mais se olhar no git pe metodo já esta lá

**Comment by robertorp** [comment]
Deu os mesmos erros que passei, no caso teria que exportar a privatekey para outro RSA para ai sim usar o signData 
Isso para certificado A1

Erro que aconteceu: Algoritmo inválido especificado.

edit: o código de abertura do tópico tem //RSACryptoServiceProvider privateKey1 = new RSACryptoServiceProvider();
            //privateKey1.ImportParameters(privateKeyProvider.ExportParameters(true));

que estão comentados, teria que ter isso para funcionar com certificado A1 mas o certificado A3 não funcionaria pois o mesmo não aceita o ImportParameters

**Comment by rftd** [comment]
Eu não tenho o certificado checa para mim se este workaround funciona.
```
var privateProvider = certificado.PrivateKey as RSACryptoServiceProvider;
if (privateProvider == null) return null;

var cspParameters = new CspParameters
{
	KeyContainerName = privateProvider.CspKeyContainerInfo.KeyContainerName,
	KeyNumber = privateProvider.CspKeyContainerInfo.KeyNumber == KeyNumber.Exchange ? 1 : 2
};

var rsa = new RSACryptoServiceProvider(cspParameters) {PersistKeyInCsp = false};

var data = Encoding.UTF8.GetBytes(CNPJSoftwareHouse + CNPJEstbComercial);
var signData = rsa.SignData(data, "SHA256");
```

**Comment by robertorp** [comment]
Deu certo, hehe pior que vi um código desse ontem no stackoverflow kkk e decidi não testar ele porque era parecido com os outros que vi e pensei.. ahh vai da treta do mesmo jeito. Ai hoje cheguei e foi testar so pra questão de conhecimento hehe.

Deu certo para A1 é Obtendo da store do windows (no meu caso é certificado A1 mas simula como se fosse A3).

`public string GerarSignAc(X509Certificate2 certificado, string CNPJSoftwareHouse, string CNPJEstbComercial)
		{
			Guard.Against<ArgumentNullException>(certificado.IsNull(), nameof(certificado));
			Guard.Against<ArgumentNullException>(CNPJSoftwareHouse.IsEmpty(), nameof(CNPJSoftwareHouse));
			Guard.Against<ArgumentNullException>(CNPJEstbComercial.IsEmpty(), nameof(CNPJEstbComercial));

			this.Log().Info($"GerarSignAc: Certificado: {certificado.SerialNumber} - CNPJSoftwareHouse: {CNPJSoftwareHouse} - CNPJEstbComercial: {CNPJEstbComercial}");

            var privateProvider = certificado.PrivateKey as RSACryptoServiceProvider;
            if (privateProvider == null) return null;

            var cspParameters = new CspParameters
            {
                KeyContainerName = privateProvider.CspKeyContainerInfo.KeyContainerName,
                KeyNumber = privateProvider.CspKeyContainerInfo.KeyNumber == KeyNumber.Exchange ? 1 : 2
            };

            var rsa = new RSACryptoServiceProvider(cspParameters) { PersistKeyInCsp = false };

            var data = Encoding.UTF8.GetBytes(CNPJSoftwareHouse + CNPJEstbComercial);
            var signData = rsa.SignData(data, "SHA256");

            var sign = signData.ToBase64();

			this.Log().Info($"GerarSignAc: Sign: {sign}");

			return sign;
		}`

Obrigado hehe, se quiser colocar no nuget nos agradece rsrs

**Comment by rftd** [comment]
Eu imaginei que fosse funcionar pois tenho um metodo para setar PIN de certificado A3 parecido que o pessoal do @ACBrNet/acbrnfse  usa e diz que funciona corretamente.
Se quizer conferir o metodo eu acho melhor que o que vocês usam la no Zeus.

https://github.com/ACBrNet/ACBr.Net.Core/blob/master/src/ACBr.Net.Core/Extensions/X509Certificate2Extensions.cs

**Comment by robertorp** [comment]
Hmm interessante, vlw, muito obrigado hehe evitou de atualizar meu projeto todo aqui para 4.6 rsrs @rftd

**Comment by rftd** [comment]
cara não anima muito com a NFe 4 vai ter que ser .net 4.5 no minimo infelizmente o TLS 1.2 so no .Net 4.5+

**Comment by robertorp** [comment]
Aqui usamos 4.5 hehe aee se quiser me add no skype as vezes podemos trocar algumas ideias.
robertoalves18@hotmail.com
