### ISSUE TITLE
CNf, NSerieSAT, NCFe devo setar eles antes de enviar para o sat?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#25]
Ou o mesmo já controla isso? Digo o aparelho que se encarrega disso?
Perguntando porque no app exemplo eles não são usados (CFeIde).

**Comment by rftd** [comment]
Baixar este arquivo que nele diz quais campos você(AC) preenche e quais o Sat preenche.

http://www.fazenda.sp.gov.br/sat/downloads/Especificacao_SAT_v_ER_2_20_06.pdf

![sem titulo](https://cloud.githubusercontent.com/assets/299476/22984914/a71b10d0-f385-11e6-9546-d62348bb19ca.png)

**Comment by robertorp** [comment]
Disso que eu precisava hehe, não tava achando ele mas imaginei que tinha algo assim.
Muito obrigado!
