### ISSUE TITLE
Tag mod - length

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#26]
Boa tarde @rftd ,
O escritório de contbilidade de um cliente meu reclamou do length da tag mod.
O meu arquivo hoje está assim:
> <  mod  > 00059< / mod >      - Ignorar os espaços, fiz isso por casa do github que ocultava a tag
Segundo ele deve ir somente 59.

Eu procurei em vários lugares e não achei nenhum manual falando sobre os campos, tamanhos e afins, então resolvi buscar nos schemas, lá está assim:

```
<xs:element name="mod" minOccurs="1" maxOccurs="1">
  <xs:simpleType>
	<xs:restriction base="xs:string">
	  <xs:length value="2"/>
	</xs:restriction>
  </xs:simpleType>
</xs:element>
```

Eu sinceramente não tenho certeza do que eu estou falando, corrigi os arquivos para ele manualmente, e mais ninguém relclamou disso, mas pelo que vi nos schemas ele não está errado...

Abraços

**Comment by rftd** [comment]
Desculpa a demora eu estou com uns problemas de saúde nos últimos dias.
Esta tag pelo manual é preenchida pelo Sat, favor conferir se o xml gerado pelo sat esta vindo correto e se é a lib que esta salvando incorretamente.

**Comment by rftd** [comment]
Eu vi aqui no codigo para salvar o XML pelo ACBrSat estava com erro o campo esta com o tamanho errado.
vou enviar uma correção.
Se estiver com pressa é so corriger nos arquivos 
CFeCancIde.cs e CFeIde.cs e mudar o tamanho minimo e maximo para 2.

[DFeElement(TipoCampo.Int, "mod", Id = "B04", Min = 2, Max = 2, Ocorrencia = Ocorrencia.MaiorQueZero)]

recompilar e já estara funcionando corretamente.
Desculpe por não envia agora se possível faça um PR.

**Comment by marcosgerene** [comment]
Boa noite,

obrigado pela atenção, corrigi localmente, tentei dar o pull por aqui mesmo mas esta pedindo pra mudar o Encoding do arquivo... não tenho pressa alguma, ja corrigi localmente e ajustei os arquivos via notepad++.

Abraços

**Comment by marcosgerene** [comment]
https://github.com/ACBrNet/ACBr.Net.Sat/pull/37
