### ISSUE TITLE
Erro na emissão: 1999 null

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#27]
tivei o sat pelo proprio app ACBR 

Cliquei em Ler OK
Cliquei em Gravar OK
Cliquei em Ativar OK
Cliquei em Acossiar assinatura OK
Cliquei em Gerar OK
Cliquei em Enviar ERRO => Erro na emissão: 1999 null 

Xml gerado
https://drive.google.com/file/d/0B22N5vYIm5Kuam01U0xDNm1jQWs/view?usp=sharing

**Comment by robertorp** [comment]
Descobri oque é

Seguindo esses passos ai que citei, ele não preenche sozinho a inscrição estadual (que deve ter 12 digitos.. se por acaso ela tiver menos que doze preencher com espaços em branco)

seria interessante deixar isso por padrão no preenchimento automatico do app teste para ninguém ter problemas enquanto a isso.

Obrigado

**Comment by rftd** [comment]
se possível faça a modificação e faça um PR para ser adicionado ao codigo.

**Comment by robertorp** [comment]
Vou fazer assim que sobrar um tempo
