### ISSUE TITLE
Qual a Pagina de Código (Arquivo codificação) ideal para o SAT?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#28]
Pagina de Codigo (por padrão no app teste é 1252 correto?)

linha aproximadamente 211 no app teste
`nunPaginaCodigo.Value = config.Get("PaginaCodigo", 1252M);`

Ai oque quero saber e interessante eu disponibilizar todas para configuração ou posso confiar somente na UTF8 e 1252?

**Comment by rftd** [comment]
A pagina de código vai depender do fabricante do Sat cada um pode usar um tipo diferente, mas estes são os mais comuns.

**Comment by robertorp** [comment]
Certo, vlw!
