### ISSUE TITLE
Componente não retorna troco (emulador)

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#29]
https://github.com/ACBrNet/ACBr.Net.Sat/issues/17 li aqui

Ai queria saber se isso foi resolvido de alguma forma? 

@marcosgerene  você conseguiu isso?

o troco é retornado 0 sempre que mando uma com troco.

**Comment by marcosgerene** [comment]
@robertorp ,
Eu acho que é um bug do emulador, quem calcula o troco é ele, em ambientes reais funciona normalmente

**Comment by robertorp** [comment]
OK, muito obrigado.
