### ISSUE TITLE
Como tratar acréscimo sobre o total no CFe?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#30]
Exemplo, tenho dois produtos na venda que custam 20 cada ou seja.. 20*2=40 e meu total atual

Eu quero dar um acréscimo no total de 20 bom ai vai para 60 meu total

beleza até aí... 

No layout de NFC-e eu acrescento tudo em prod.vOutro
lendo o manual página 91 eu posso adicionar o acresimo lá também

Eu adiciono no _cfeAtual.InfCFe.Total.VCFe = 60;
logo em seguida faço os lançamentos dos pagamentos no caso um unico pagamento de 60 em dinheiro

ele me retorna erro "Erro no campo 'vCFe' : Campo vCFe maior que a soma dos valores do MP.
sendo que ele é igual

**Comment by leandrossantos** [comment]
@robertorp boa tarde, não sei se você fez isso: incluiu o acrescimo no vOutro dos itens também, pois na NFe ou NFCe tem que inclui no vOutro dos itens também.

**Comment by robertorp** [comment]
Fiz exatamente isso
Olha o xml como ficou 

https://paste.ofcode.org/rRLf9DFJJnr8zNHA7rn4iF

**Comment by leandrossantos** [comment]
@robertorp 

Pelo que vi no código do XML que mandou. Se entendi bem no caso do CFe quando tem acréscimo ou desconto no total não precisa usar os campos vDesconto ou vOutro do produto e dos totais. Basta informar no bloco **DescAcrEnt** como está selecionado na imagem abaixo, É a segunda seleção que fiz.
Deixe somente com ele e faça o teste.

[http://prntscr.com/ejyzth](http://prntscr.com/ejyzth)

**Comment by robertorp** [comment]
@leandrossantos , deu certo, mas.. somente uma questão é coerente deixar o xml assim? sem preencher esses outros campos que retirei? (na nfc-e já sou obrigado a ter eles)

https://paste.ofcode.org/Zg8AJPQtCiUqZJRUYnJXZq

**Comment by leandrossantos** [comment]
@robertorp não sei lhe dizer ao certo, ainda não mexi com SAT. Por enquanto estou mexendo apenas com NFe, NFCe, MDFe e CTe. O SAT será minha próxima etapa, o que falei falei apenas uma sugestão analisando o XML que você enviou. Dá uma olhada no manual ou até mesmo consulte algum contador para saber se está correto isso que foi feito e acabou dando certo.

**Comment by rftd** [comment]
Como pode ver abaixo tem a explicação do manual.

![sem titulo](https://cloud.githubusercontent.com/assets/299476/23920408/e4ec0d8c-08d0-11e7-92cb-a15f24073d2a.png)

Ou seja o vOutro ou vDesc é para acrescimo/desconto no item. 

Lembrando que o VCFe não é informado pelo AC e sim pelo SAT.

![sem titulo](https://cloud.githubusercontent.com/assets/299476/23920573/a2c40a9e-08d1-11e7-8d8b-a7fc76e68686.png)

Obs.: no Sat tem desconto e acrescimo no subtotal também e so pode ser informado 1 dos dois não sei se o mesmo se aplica aos itens.

**Comment by robertorp** [comment]
Já fazendo testes aqui, quando informo um desconto primeiro.. e logo em seguida um acrescimo ele cria o xml assim 

`<total>
         <vCFe>15.00</vCFe>
         <DescAcrEntr>
            <vDescSubtot>35.00</vDescSubtot>
            <vAcresSubtot>5.00</vAcresSubtot>
         </DescAcrEntr>
      </total>`

logo então da erro dizendo que os valores de desconto e acresimo sobre o subtotal são mutamente exclusivos , ou seja somente posso criar um soh? correto? isso que entendi?

@rftd vOutro valor de acresimos sobre o valor do item, já o vdesc é para desconto... mas como falei quando informo o voutro e mando pagar o MP = 60 ele difere o valor do total.. sendo eu imagino que o total seria 60 pois ajustei o valor para mais .

@rftd existe alguma maneira de min debugar o emulador?  (logs coisas do tipo)
update..

**Comment by rftd** [comment]
Sim so pode ter ou desconto ou acrescimo no subtotal.
Não é possivel debugar o emulador.
Obs: aparentemente é bug do emulador mesmo informando corretamente os campos não funciona.

**Comment by robertorp** [comment]
Fechou
