### ISSUE TITLE
getXml() retornando juntamente com o cabeçalho padrão de todos xmls existentes

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#31]
`<?xml version="1.0" encoding="utf-8"?>
<CFe>
  <infCFe versaoDadosEnt="0.07">
    <ide>
      <CNPJ>22222222222222</CNPJ>
      `

uma parte do xml gerado pelo componente...
digo precisa necessáriamente o componente retornar isso <?xml version="1.0" encoding="utf-8"?>?
observação: toda vez que vou salvar o xml no banco de dados da esse erro 
XML parsing: Line 1, character 38, can not switch encoding

aqui é somente para trocar uma ideia sobre qual a melhor forma de manipular o xml mas se for isso ok.. 
observação o erro acontece quando uso tipo de dados "xml" do sql server

**Comment by robertorp** [comment]
Ahh agora que vi tenho isso aqui 

var xml =
                _cfeAtual.GetXml(encoding: Encoding.Unicode);

bom ai deu certo,
obrigado

**Comment by rftd** [comment]
Então roberto maioria dos softwares usam a codificação UTF8 inclusive a receita por isto é o enconding padrão mas como você descobriu pode ser alterado para outros, lembrando que se for mandar para seu contador provavelmente seria correto enviar em UTF8
