### ISSUE TITLE
Códigos de erro e mensagens de erro

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#32]
para min o retorno sempre chega o código do erro, mas a mensagem nem sempre chega

Quando o erro é "Os valoes de desconto e acrescimo sobre o subtotal sao mutamente exclusivos bla bla bla "

Erro no campo 'total' 

Erro na emissao: 1999: null

eu forcei o erro intencional para ver oque ele manda para trás
talvez ele deveria ter o erro lançado para trás a mensagem "Os valores bla bla etc.." 

ai queria saber se em produção com o equipamento ele lança o erro certinho...

**Comment by rftd** [comment]
Não sei te dizer pois os erros conhecidos estão catalogados no manual do SAT qualquer outro erro que não esteja la vai vir erro desconhecido ou seja 1999.
Por isso boa parte dos fabricantes tem um logo extendido que geralmente da para se pegar usando o programa dos mesmos.

**Comment by robertorp** [comment]
Sim digo, no manual vi aqui, negocio é pode implementar para o componente? Pelo menos os padrões que estão no manual do SAT.

**Comment by rftd** [comment]
Qualquer contribuição que queira fazer é bem vinda desde que não afete o funcionamento atual para não atrapalhar quem já usa o componente.
É so fazer as modificações e fazer um PR para analise.

**Comment by robertorp** [comment]
Estou criando uma extenção (class ext) para isso.
Acho que logo posto ela, to testando já no nosso sistema aqui.

**Comment by robertorp** [comment]
@marcosgerene  Sabe me informar se o sat retorna somente códigos mesmo? Digo ate os códigos de erros? Porque pelo que estou vendo aqui, os códigos de erros nada mais são que rejeições somente isso. Mas o emulador não retorna a mensagem de erro (ou o componente) . Bom você que usa na pratica oque me diz sobre isso? ele retorna as mensagem corretamente ou não ?

**Comment by marcosgerene** [comment]
@robertorp 

Os retornos de erro do SAT são muito confusos pra mim até hoje, quando eu tenho um problema mais chato eu tenho que recorrer ao LOG do sat ou analisar o XML do arquivo enviado...

Eu fiz alguns tratamentos no sistema do tipo só aceitar CST 49 para pis e cofins no caso do SAT para simples nacional e coisas assim.... e todos meus clientes SAT até agora são Simples Nacional, então para ser sincero, faz uns 60 dias que não tenho que dar suporte para SAT e devo ter em torno de uns 20 clientes com SAT em produção +/-
