### ISSUE TITLE
Componente não captura a mensagem da sefaz no cancelamento

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#35]
No emulador do SAT eu seto uma mensagem vou em

Opções Emulador Off-Line
Envio de aviso ao usuário (digito oque quero)

mando cancelar uma CF-e e a mensagem não cai no campo resposta.MensagemSEFAZ

Aqui solucionei pegando o elemento da posição 5 do list de retornoLista

**Comment by robertorp** [comment]
na troca de código ativação ocorreu isso também

observação estou utilizando emulador da sefaz

**Comment by rftd** [comment]
vou verificar e corrigir

**Comment by rftd** [comment]
Pelo que eu vi no cancelamento é um erro do emulador ele deveria enviar ali no campo CCCC um código de 4 digitos e o mesmo não vem por isto não cai no if e a mensagem não é pega corretamente.
