### ISSUE TITLE
MFE - Ceará

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#36]
Boa noite @rftd ,

Estou com um conjunto de clientes no Ceará me questionando sobre o MFe.

Sou de SP e não fazia ideia do que se tratava e após pesquisa vi que se tratava de um "SAT modificado".

Você saberia dizer se a biblioteca presente aqui funcionaria para MFe?

**Comment by robertorp** [comment]
Se não me engano muda 3 métodos.. mas acho que nem um dos métodos em questão irá atrapalhar sua venda. (Bom não sei enquanto ao layout do xml se teve mudanças ou não)
esse tópico no acbr ajuda bastante
http://www.projetoacbr.com.br/forum/topic/30121-equipamento-mfe-sat-cear%C3%A1/

**Comment by rftd** [comment]
O MFe é basicament um Sat Cearense a diferença é 3 funções extras e que a dll é fornecida pela Sefaz e não por cada fabricante.

**Comment by marcosgerene** [comment]
Boa noite @robertorp e @rftd,

Eu estava lendo justamente o topico levantado pelo Roberto antes de postar, na verdade ja solicitei um aparelho de testes para a Tanca também para só testar o que já tenho pronto.

Acredito que teremos mudança apenas no Extrato que deverá ter no cabeçalho o nome MFe ao invés de SAT, as 3 funções adicionais acredito não vou usar no dia-a-dia.

Att, Marcos
