### ISSUE TITLE
nItem ser preenchido pelo componente

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#38]
nItem ser preenchido pelo componente, motivo, hoje testando emissão aqui eu adicionei dois itens

cancelei o item 1 meu..
meu AC adicionou nItem=2 pois foi oque sobrou.. 

bom ele deu rejeição dizendo que os números não estavam em ordem, bom o erro foi eu no caso
mas seria interessante se no lugar de min eu preencher esse campo o SAT preenchesse ele, já que eles devem obrigatoriamente estarem em ordem 1,2,3,4,5,6,7,8 etc..

logo então não vejo motivo para não ter isso automático pelo componente
antes de enviar para o ac o componente poderia percorrer todos itens adicionando 
```
for (..) {
    nItem = numeroItem;
    numeroItem++;
}
```

E somente uma dica de uma melhoria que pode ter ou não pode ter. 

Aqui to usando um SAT SDK TANCA para o teste

**Comment by rftd** [comment]
Não vejo a necessidade de ser preenchido pela classe mas podemos gerar um método de extensão que faça o mesmo ai fica opcional para cada um usar se quiser

**Comment by rftd** [comment]
https://github.com/ACBrNet/ACBr.Net.Sat/commit/c31bf49c8502c9ae0226f103282f3123b29b0861

**Comment by leandrovip** [comment]
Eu iria abrir outra issue, mas o motivo está relacionado diretamente com esta, por isso vou comentar aqui.

Estou utilizando a função **PreencheNItem** mas ela não funcionou de acordo com o propósito, na atribuição do valor _NItem_ a variavel i do vetor é alterada:

`det.NItem = i++; `

Fiz um teste e alterando da forma abaixo resolveu o problema, seria isso?

`det.NItem = i + 1; `

[]´s
