### ISSUE TITLE
MFE - integrador

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#39]
Bom dia @rftd,

A um tempo atrás perguntei pra você sobre o MFE e a conclusão final foi que o SAT hoje já disponivel atenderia o MFE. Entretanto, ao pesquisar mais afundo sobre o projeto notei que o MFE necessita de um integrador que trata sobre pagamentos e sinceramente fiquei perdido sobre qual o sentido do integrador.

Você já tem noção de como esse integrador interfere na rotina da emissão do cupom?

**Comment by rftd** [comment]
Sim a Sefaz CE teve a brilhante ideia de estragar o SAT que já não era uma maravilha, agora a comunicação é toda feita através de um integrador por monitoramento de pasta, ou seja o negocio vai ficar muito mas lento e trabalhoso, sendo necessário muitas modificações no ACBrSat atual para funcionar corretamente, e sem falar que para o integrador funcionar tu precisa que cadastrar la na SEFAZ para liberação de uso.

**Comment by leandrossantos** [comment]
Bom dia, @rftd  e @marcosgerene.
Vejam se estou equivocado ou é isso mesmo. Essa MFE do CE é somente para a questão do CFe ou NFCe igual funciona em SP ou a NFe entra nessa jogada também?

**Comment by rftd** [comment]
No Ceara a NFCe vai ser igual em SP contigencia para o MFe e também será necessário usar o maldito integrador fiscal da sefaz e toda venda por cartão tem que ser enviado para o integrador também para um outro sistema da sefaz que cuida do de cartão de crédito.

**Comment by leandrossantos** [comment]
Então @rftd o MFe é somente para CFe e NFCe é isso?
Ou se na NFe tiver venda por cartão terá que usar o MFe também?

**Comment by rftd** [comment]
MFe é para CFe e NFCe vai usar o integrador da SEFAZ CE
Vai ser igual em Sao Paulo para usar a NFCe tem que ter o MFe e no caso do CE o integrador da SEFAZ.

**Comment by marcosgerene** [comment]
@rftd, estava bom pra ser verdade... bem, vamos trabalhar, aonde conseguiu essas informações? existe algum material de estudo prático e não encontrei ou está tudo nebuloso mesmo?

**Comment by rftd** [comment]
Esta informações peguei no fórum do ACBr com o povo que faz parte de um Grupo de Whatsapp da MFe

Como instalar o maldito integrador e um FAQ basico
http://www.projetoacbr.com.br/forum/topic/36473-faq-mfe-como-iniciar-o-desenvolvimento-usando-o-m%C3%B3dulo-integrador/

**Comment by marcosgerene** [comment]
@rftd obrigado
