### ISSUE TITLE
Alteração para uso em API 

### ISSUE THREAD

**Issue by ThallesMendes** [ACBrNet/ACBr.Net.Sat#40]
Estou desenvolvendo uma API que receberá requisições de varios caixas e processara em fila no equipamento sat na intranet.
A questão que instanciar um objeto ACBrSAT na criação automatica do objeto CfgArquivos eu recebo um erro de NullPointException na linha 
`var path = Assembly.GetEntryAssembly().GetPath();`
eu fiz uma pesquisa rapida e modifiquei a linha para 
`Assembly entryAssembly = new StackTrace().GetFrames().Last().GetMethod().Module.Assembly;
 var path = entryAssembly.GetPath();`

Agora esta funcionando corretamente, gostaria de saber se minha metodologia esta correta, e se sim recomendar a alteração nos fontes originais. Obrigado

**Comment by rftd** [comment]
Eu vou dar um olhada no caso você esta utilizando no IIS correto ?

**Comment by ThallesMendes** [comment]
Estou usando o IIS Express do proprio visual studio 2015

**Comment by rftd** [comment]
as app para web tem uns esquemas diferentes para pegar path, vou ver o que posso fazer para resolver

**Comment by ThallesMendes** [comment]
Entendo, eu modifiquei o codigo daquela maneira. Ele pegou um path totalmente contrario do que eu realmente vou usar, por isso eu configuro todo o componente em uma classe da minha aplicação.

Eu ja trabalhava assim no delphi utilizando SOAP.

De qualquer maneira muito obrigado

**Comment by rftd** [comment]
è que a lib não foi feita pensando em uso web da mesma devido os problemas para usar as coisa quando estiver no servidor por exemplo acesso a path, acesso a lib nativa
principalmente se hospedar em outro lugar tipo amazon e azure

**Comment by ThallesMendes** [comment]
Sim, se fosse para hospedar na web não funcionaria mesmo não, mas em um ambiente com varios caixas, utilizar de um SAT só utilizando a própria fila do servidor IIS para gerenciar as requisições de emissão fica um processo bem pratico. Ja venho utilizando assim no SOAP do delphi 7 a um ano, mas devido os componentes acbr estarem perdendo a compatibilidade com versões antigas do delphi, resolvi desenvolver usando o .net.

**Comment by rftd** [comment]
Tenta mudar para Assembly.GetExecutingAssembly().GetPath();

**Comment by ThallesMendes** [comment]
Assim funcionou
