### ISSUE TITLE
Erro ao deserializar o objeto nCFe

### ISSUE THREAD

**Issue by ThallesMendes** [ACBrNet/ACBr.Net.Sat#42]
Estou fazendo a emissão de documentos fiscais utilizando o componentes, mas em alguns arquivos XML especificos ao utilizar o metodo Load da classe CFe, ele lança a exception "Erro ao deserializar o objeto nCFe". A questão que o erro ocorre apenas em alguns arquivos XML, e ja fiz a comparação varias vezes de um arquivo que funciona e outro que funciona, e não tem nenhuma diferença relevante nos mesmos.
O erro ocorre ao carregar o conteúdo desse arquivo :
[30121899100834.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/1052218/30121899100834.txt)
Mas não ocorre ao carregar :
[30121899100723.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/1052221/30121899100723.txt)

Analisando o conteúdo de ambos percebesse que não existe diferença relevante, e eu não estou conseguindo carregar o projeto Dfe.Core no meu visual studio para debugar.

Aguardo resposta.

**Comment by rftd** [comment]
No Xml a TAG ICMS do grupo Imposto
 esta vazio a mesma não deveria ser informada caso não tem este imposto por isto o erro ele tenta desserializar a tag e não tem nada nela.

![sem titulo](https://cloud.githubusercontent.com/assets/299476/26790562/32c85752-49e2-11e7-97c5-6cb6ba223768.png)

**Comment by ThallesMendes** [comment]
Certo, entendi, é que a responsabilidade de montagem do meu XML está em uma aplicação delphi, e o meu sistema estava informando CSOSN 101, que não pode ser usado em documento CFe, por isso ele monta a TAG vazia, creio que agora que mudei a inteligencia do gerador do arquivo vai funcionar.

Muito obrigado a atenção.
