### ISSUE TITLE
ERRO AO ABRIR O PROJETO.

### ISSUE THREAD

**Issue by itsmehps** [ACBrNet/ACBr.Net.Sat#43]
Quero abrir o projeto para dar uma estudada, mas estou com vários erros, não consigo executar a solução, será que fiz algo de errado? eu baixei os arquivos do GIT abri a solução, defini o Acbr.Net.Sat.Demo como projeto de abertura, peguei o package do ACBr.Net.Sat 1.0.1.5 pelo NUGET mas ele me retorna 325 WARNINGS com o Código C24036, e alguns erros como o de não encontrar MFeResposta, The name Resposta does not exist, MetaData file Acbr.Net.Sat.dll could not be found (Nesse caso eu peguei a DLL do SAT, joguei na pasta, mas continua com esse erro), o que será que não fiz certo? pode me ajudar?

**Comment by marcosgerene** [comment]
Utilize a versão do Nuget que está estável ao invés da versão mais nova.

Ou puxe para seu fork o pull https://github.com/ACBrNet/ACBr.Net.Sat/pull/41 que este problema foi sanado, o componente está sendo ajustado para implementar também o MFe (projeto equivalente ao SAT para o estado do Ceara) conforme https://github.com/ACBrNet/ACBr.Net.Sat/issues/39

**Comment by Herbert2122** [comment]
La no site da NUGET já usei a versão mais estável, mas testei com a versão anterior 1.0.1.3 também não dei certo, não estou conseguindo fazer o FORK, não tem algum arquivo ZIP sem os erros? :(

**Comment by itsmehps** [comment]
Obrigado!!!
