### ISSUE TITLE
INTEGRAÇÃO IMPRESSÃO / VB.NET / DÚVIDAS

### ISSUE THREAD

**Issue by itsmehps** [ACBrNet/ACBr.Net.Sat#44]
Sobre a integração com o FAST REPORTS, eu realmente preciso comprar a licença dele correto? Pois vi que é pago.

Eu estou pensando em converter esse código para vb.net, pois as aplicações que tenho são tudo em VB.NET, acha que eu teria grandes dificuldades?

Existe alguma outra ideia de implentação de extrato, sem usar componentes pagos?

**Comment by marcosgerene** [comment]
Boa noite,

*Sobre o fast-reports:*

Ele é pago mas existe a versão demo que é gratuita e a unica diferença que não vai sair uma marca d'água escrito "DEMO VERSION" em diagonal na impressão que aparece apenas na impressão ou quando exporta (ex: PDF).

Eu uso o fast-reports no meu dia a dia, pois foi o melhor componente de relatórios que me atendia nas minhas necessidades especificas como o fato de eu gerar meus relatórios baseados em List de objetos e não em conexão direta ao banco, e o custo beneficio da ferramenta é interessante, no mundo .Net foi a melhor engine de relatorios que encontrei e com um preço relativamente acessível.

*Sobre componentes free:*
Existe a possibilidade de implementar uma impressão nativa, se eu fosse fazer algo assim me inspiraria no que é feito hoje no Zeus (https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe), lá existe duas opções de impressão em Fast Reports e nativo ("na unha").

Nada impede também que você implemente em outro gerador de relatórios que prefira, o projeto é open-source... 

Agora se você precisa de algo "pronto" e a custo zero, use o ACBrMonitor (http://acbr.sourceforge.net/drupal/?q=node/19) somente para a impressão (não gosto dessa opção, acho que é cria mais uma dependencia pro projeto pra você cuidar e afins, mas é free e funciona bem).

**Comment by itsmehps** [comment]
ÓTIMO obrigado pelos esclarecimentos, e em questão da conversão para VB.NET? Eu fiz uns testes iniciais mas tive alguns problemas.

**Comment by rftd** [comment]
Não precisa nenhuma conversão para VB.Net todo código em .Net pode ser usado em qualquer linguagem da plataforma independente de qual seja.
Eu posso usar esta lib em vb.net, c#, f#, IronPython e etc...

**Comment by itsmehps** [comment]
No caso @rftd eu me referia, as funções, por exemplo: GerarVenda(), CancelarVenda(), etc, no caso do demo, elas foram escritas em C#, sendo assim caso eu precise converter aquele código, para implementar na minha aplicação vb.net, não terei problemas correto?

**Comment by rftd** [comment]
não pode utilizar da mesma maneira sem problema algum.

**Comment by itsmehps** [comment]
Obrigado por esclarecer, mais uma dúvida no caso o que seria StdCall, e Cdecl, em qual caso usar para um comércio por exemplo?

**Comment by marcosgerene** [comment]
@Herbert2122 StdCall e Cdcel são formas de chamar uma dll.

https://stackoverflow.com/questions/3404372/stdcall-and-cdecl

Use Cdecl para a DLL do emulador e Stdcall para as dlls dos equipamentos.

**Comment by itsmehps** [comment]
Obrigado novamente a vocês, pelo suporte e esclarecimento.

**Comment by rftd** [comment]
Maioria dos fabricantes usa stdcall para maior compatibilidade, leia VB6 e anteriores.
Mas pode ter fabricantes que usam cdcel eu nunca vi ainda mas pode ser um possibilidade

**Comment by marcosgerene** [comment]
>Maioria dos fabricantes usa stdcall para maior compatibilidade, leia VB6 e anteriores.
>Mas pode ter fabricantes que usam *cdecl* eu nunca vi ainda mas pode ser um possibilidade

@rftd provalmente nem exista, pois algo assim pode limitar o "alcance" do fabricante  em vendas para quem usa softwares com tecnologia legada, na minha visão não seria estratégico

**Comment by itsmehps** [comment]
Caros me ajudem com outras dúvidas, ultilizando a DLL fornecida pela SEFAZ, eu consigo efetuar testes? Com essa DLL consegui fazer algumas rotinas, porém outras não, como por exemplo ENVIAR VENDA, o programa não dá erro, porém congela, achei que com essa DLL eu conseguiria simular todas as rotinas.

e outra dúvida: 

No caso de produção, como eu faria o Envio de uma lista de produtos ?, no evento GERACFE eu vi que tem a variável 

XProd, no caso como eu incluiria vários produtos?

eu sei que a segunda pergunta pode parecer besta, mas é que não tenho muita vivencia com o C#, só domino o vb.net, ainda estou tentando entender como o C# funciona.

**Comment by marcosgerene** [comment]
> o programa não dá erro, porém congela, 

O emulador esta fechado, a DLL "prende" a aplicação até ter a resposta do emulador.

![emulador](https://user-images.githubusercontent.com/15945003/26837065-d69ca4fc-4ab2-11e7-9d9e-8a3e00c18200.png)

> achei que com essa DLL eu conseguiria simular todas as rotinas.

Não consigo afirmar todas, porque eu mesmo não implemento funcionalidades como bloquear/desbloquear no meu sistema, faço isso com o soft. da fabricante para evitar problemas, mas no que envolve o dia a dia como vender, cancelar e afins é totalmente possivel testar com o emulador.

> No caso de produção, como eu faria o Envio de uma lista de produtos ?, no evento GERACFE eu vi que >tem a variável XProd, no caso como eu incluiria vários produtos?

![add itens](https://user-images.githubusercontent.com/15945003/26837082-e0d4c7ce-4ab2-11e7-8e1c-c2bccfb37efe.png)

```
var det = cfe.InfCFe.Det.AddNew(); 
det.Propriedade =Valor;
...
```

>eu sei que a segunda pergunta pode parecer besta, mas é que não tenho muita vivencia com o C#, só domino o vb.net, ainda estou tentando entender como o C# funciona.

A tendencia é piorar, cada dia que passa descubro que sei menos ;)

**Comment by itsmehps** [comment]
Obrigado @marcosgerene , você SABE esclarecer se eu preciso mexer no cálculo de impostos etc??? Ou esse DEMO já faz tudo corretamente? No caso para o estado de SÃO PAULO.

E se existe alguma forma de cadastrar o Software House como pessoa fisica? No caso eu realmente como desenvolvedor individual, vou precisar criar uma empresa, comprar o certificado digital, para daí então registrar o software, correto?

E digamos para simplificar qual seria a ordem de uso dia a dia do componente?

GerarCfe()
EnviarVenda()
Imprimir()

E nos casos necessários
GeraXmlCancelamento()
EnviarCancelamento()
ImprimirCancelamento()

Correto?
Ou eu preciso fazer alguma coisa antes tipo Inicializar ou algo assim?

Como eu faço a emulação de uma venda pelo DEMO ?
Qualquer opção que usa o sat ele dá o erro "Não foi possivel carregar a biblioteca Sat"

**Comment by marcosgerene** [comment]
>Obrigado @marcosgerene , você SABE esclarecer se eu preciso mexer no cálculo de impostos etc??? Ou >esse DEMO já faz tudo corretamente? No caso para o estado de SÃO PAULO.

É você quem calcula os impostos, o componente somente pega o objeto que você preencheu, serealiza (transforma em XML) e envia pra a DLL que envia ao aparelho.

> E se existe alguma forma de cadastrar o Software House como pessoa fisica? No caso eu realmente como > desenvolvedor individual, vou precisar criar uma empresa, comprar o certificado digital, para daí então >registrar o software, correto?

Não pode ser pessoa física, deve ser empresa ter CNAE de desenvolvedor (que infelizmente não se encaixa como MEI então tem que ser ME ou EPP) e tem que ter o certificado digital, pois a chave para assinatura do AC será gerado com o certificado da software house.

>E digamos para simplificar qual seria a ordem de uso dia a dia do componente?
>GerarCfe()
> EnviarVenda()
>Imprimir()
> E nos casos necessários
> GeraXmlCancelamento()
> EnviarCancelamento()
> ImprimirCancelamento()

1. Inicializar
2. Preencher o componente (gerar)
3. enviar venda
4. se a venda for enviada, imprimir.
5. Desinicializar


1. Inicializar
2. preencher o componente para o cancelamento
3. enviar o cancelamento
4. imprimir o cancelamento
5. Desinicializar

Sempre "desinicialize" para liberar o uso da DLL.

>Como eu faço a emulação de uma venda pelo DEMO ?
>Qualquer opção que usa o sat ele dá o erro "Não foi possivel carregar a biblioteca Sat"

Este erro ocorre quando a dll não está no caminnho informado na propriedade "PathDll"

**Comment by Herbert2122** [comment]
Então mas nesse caso a biblioteca está no local correto. C:\SAT\SAT.dll, ele permanece com o erro.e ai eu não consigo fazer nada de testes.

**Comment by itsmehps** [comment]
Obrigado @marcosgerene , me tira uma dúvida, peguei a versão FAST REPORTS mas com ela não consigo me comunicar com o SAT OFFLINE, no caso com a última versão funciona tudo que é uma beleza, porém quando vou fazer a impressão, ele dá um erro " Value cannot be null." ou o erro "Componente não está ativo." tentei fazer a cópia do código do projeto que tem fastreport para o que não tem, mas deu bastantes erros. Mas só para entender, em tese a impressão do componente, pega os dados do XML gerado, e imprime no formato lá do cupom correto?, se para gerar XML eu preciso preencher, a impressão seria pegar esses dados do XML, e imprimir no cupom, correto?

**Comment by marcosgerene** [comment]
@Herbert2122 não entendi nada...

**Comment by itsmehps** [comment]
Marcos de forma mais clara :

Peguei aquela versão do projeto que é denominada "Acbr Net Sat fast reports"
Porém com esta versão do projeto. Eu não estou conseguindo enviar o comprovante ou fazer qualquer outra comunicação com o aparelho Sat. Ele informa "Não é possível carregar a biblioteca". Me parece que esta é uma versão antiga do projeto. 
Com a versão atual do Git Hub. A versão onde abri está issue. Eu consigo fazer as comunicações com o aparelho Sat. Porém ela não tem as rotinas de impressão. Então eu quero esclarecer se. No caso da impressão. Ele pega os valores do XML e faz a impressão? É somente isso?  Pois queria algo que emulasse mas com o projeto que contém o Fast Reports eu não consegui. E assim vou tentar fazer de outra forma.

**Comment by marcosgerene** [comment]
O projeto que contem o fast report é o projeto de impressão de SAT e ele usa este projeto do SAT referenciado via Nuget, são a mesma coisa, a impressão e o "componente em si" são projetos separados,
mas a impressão usa este.

Limpa suas referencias ao Nuget do Acbr.net e referencia diretamente a impressão, o proprio visual studio será inteligente para referenciar as dependencias como este projeto em si, o .dfe.core e o .core

**Comment by Herbert2122** [comment]
Obrigado @marcosgerene  fiz conforme orientações e agora o projeto abre, porém na hora da impressão, já no FastReport ele dá o erro: "Erro CS0103 The Name Regex  does not exist in the current context" eu vi que parece algo relacionado a chave de acesso. Sabe como proceder?

**Comment by itsmehps** [comment]
Obrigado @marcosgerene , consegui testar agora. Obrigado pela paciencia kkkk.

**Comment by itsmehps** [comment]
Uma dúvida final, no projeto desta issue, eu vejo que o Projeto ACbr.Net.Sat, tem vários outros namespaces, coisa que o projeto que contém a impressão não tem. Coisa como CfeEntrega, CfeDetImposto, sabe me dizer o que é?, se tem alguma grande diferença daquele que contém a impressão, ou não, ambos tem as mesmas funcionalidades?

**Comment by marcosgerene** [comment]
ACBr.Net.Sat é um projeto, ACBr.Net.Sat.Extrato.FastReport é outro projeto, porém o segundo depende do primeiro, ou seja, você pode usar o ACBr.Net.Sat sem usar o extrato mas não pode usar o extrato sem usar o ACBr.Net.Sat, até aqui ok?

EX: eu não tenho o fast reports, e vou usar outra ferramenta para imprimir mas vou usar o ACBr.Net.Sat para gerar e enviar o SAT.

Ex 2: eu  vou gerar o SAT com outra ferramenta mas vou usar o ACBr.Net.Sat.Extrato.FastReport para imprimir.

Ambos são projetos que se complementam, mas o extrato (impressão) usa o ACBr.Net.Sat para pegar o XML e transformar em um objeto CFe e imprimir.

Quer um exemplo melhor? você. rsrs... tipo, se vc fizer um projeto que pegue o xml que foi gerado e transmitido e imprima usando ACBr.Net.Sat você estará fazendo um "ACBr.Net.Sat.Extrato.FastReport" próprio. Entendeu?

----


Acredito que você já deduziu isto com a explicação acima, mas respondendo sua pergunta, o que tem no ACBr.Net.Sat.Extrato.FastReport tem no ACBr.Net.Sat e vice e versa, porque o projeto aonde estão as classes e o SAT em si é o ACBr.Net.Sat e o extrato referencia ele via nuget para imprimir

**Comment by itsmehps** [comment]
Ficou bem claro agora, muito obrigado @marcosgerene .
