### ISSUE TITLE
Importar no projeto

### ISSUE THREAD

**Issue by ghost** [ACBrNet/ACBr.Net.Sat#47]
Amigo boa tarde, como que eu posso fazer pra importar no meu projeto ?
É só adicionar a .dll nas referencias ?

**Comment by marcosgerene** [comment]
Boa tarde,

Sim, o projeto é para .net, se você usa vb.net ou c#.net basta referenciar o projeto.

Acredito que a forma mais simples seja referenciar via Nuget.

**Comment by wesleycosta** [comment]
Boa tarde, desculpa a minha ignorância.
Quando eu seleciono a opção "imprimir extrato de venda" em "venda" no menu superior, gera a seguinte exceção:

Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

**************** Texto de Exceção **************
ACBr.Net.Core.ACBrException: Componente não está ativo.
   em ACBr.Net.Core.Exceptions.Guard.Against[TException](Boolean assertion, String message)
   em ACBr.Net.Sat.ACBrSat.ImprimirExtrato(CFe cfe)
   em ACBr.Net.Sat.Demo.FrmMain.imprimirExtratoVendaToolStripMenuItem_Click(Object sender, EventArgs e) na e:\SAT_ACBR\ACBr.Net.Sat-masterA\src\ACBr.Net.Sat.Demo\FrmMain.cs:linha 391
   em System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   em System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   em System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   em System.Windows.Forms.ToolStripItem.ProcessDialogKey(Keys keyData)
   em System.Windows.Forms.ToolStripDropDownItem.ProcessDialogKey(Keys keyData)
   em System.Windows.Forms.ToolStrip.ProcessDialogKey(Keys keyData)
   em System.Windows.Forms.ToolStripDropDown.ProcessDialogKey(Keys keyData)
   em System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   em System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   em System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)**


Bom acredito que esta faltando referenciar o "ACBr.Net.Sat.Extrato.FastReport", porem não estou conseguindo...

Agradeço pela atenção e parabéns pelo trabalho!
