### ISSUE TITLE
Erro impressão FastReport

### ISSUE THREAD

**Issue by AlanJovita** [ACBrNet/ACBr.Net.Sat#48]
Boa noite, pessoal
Implementando Cupom fiscal SAT e o projeto está me ajudando muito e estou tendo ótimos resultados, parabéns a iniciativa e dedicação de todos envolvidos espero poder contribuir para o projeto também. 

Hoje passei o dia em desenvolvimento e estou com um erro abaixo, alguém já superou o mesmo ? 

**## FastReport.Utils.CompilerException: (206,30): Erro CS0103: O nome 'Regex' não existe no contexto atual.**

ele aparece quando vou enviar o comando de 'Imprimir Extrato de venda'.

Grato desde já.

**Comment by marcosgerene** [comment]
Boa noite,

Qual versão do Fast Reports está usando e como fez a referencia às DLLs do FastReports no seu projeto?

**Comment by rftd** [comment]
Eu acho que tem haver com uma modificação que fiz recente e não tive tempo de testar eu vou dar uma olhada.

**Comment by rftd** [comment]
Corrigido no ultimo commit no repositório.
