### ISSUE TITLE
Imprimir Extrato de Venda

### ISSUE THREAD

**Issue by wesleycosta** [ACBrNet/ACBr.Net.Sat#49]
Boa noite, desculpa pela ignorância.
Como que eu faço para imprimir um extrato de venda?

Agradeço pela atenção e parabéns pelo trabalho.

**Comment by rftd** [comment]
Você tem que associar um componente de impressão ao ACBrSat tem o [ACBr.Net.Sat.Extrato.FastReport](https://github.com/ACBrNet/) que é feito usando o gerador de relatórios Fast Report, você pode usar ele de exemplo para criar um próprio se quiser.

**Comment by wesleycosta** [comment]
Bom dia,
Quando eu inicializo o sat aparece a exceção "Não foi possível carregar a biblioteca SAT"
![captura de tela 70](https://user-images.githubusercontent.com/3426975/29271673-0a956cac-80d3-11e7-908a-71d22fee4ebc.png)
Porem o caminho da dll está correto. Outra coisa que percebi é que quando tento inicializar o sat no sistema que estou desenvolvendo gera essa exceção, quando eu crio um projeto novo não gera.
Sera que pode ser algum conflito que esta causado isso dentro da minha solução em produção?

**Comment by wesleycosta** [comment]
Bom dia,
Quando eu inicializo o sat aparece a exceção "Não foi possível carregar a biblioteca SAT"
![captura de tela 70](https://user-images.githubusercontent.com/3426975/29271673-0a956cac-80d3-11e7-908a-71d22fee4ebc.png)
Porem o caminho da dll está correto. Outra coisa que percebi é que quando tento inicializar o sat no sistema que estou desenvolvendo gera essa exceção, quando eu crio um projeto novo não gera.
Sera que pode ser algum conflito que esta causado isso dentro da minha solução em produção?

Agradeço pela atenção.

**Comment by rftd** [comment]
Provavelmente você esta errado a convenção da dll do sat se estiver usando cdecl usa stdcall.
Se mesmo assim não der certo então o problema é teu sistema é x64 e tu ta carregando um dll x86.
E por favor em caso de duvida diferente abra uma nova issue.

**Comment by wesleycosta** [comment]
Value Rafael !!! era isso mesmo...
Na compilação do meu projeto estava como "Any CPU" mudei para "x86" e pegou...
