### ISSUE TITLE
Ativar - Não foi possivel carregar a biblioteca Sat

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#5]
Quando chamo a função ativar recebo o seguinte Exception: "Não foi possivel carregar a biblioteca Sat".

 O Path do Dll está ok, não alterei o Encoding e tentei com cdcel e stdcall.
O demo funciona perfeitamente, o meu software não, porém ao debugar vi que os parâmetros são passados de forma idênticas nos dois casos (meu soft. e o DEMO).

Nas minhas dependências adicionei o ACBr.Net.Core, ACBr.Net.DFe.Core e ACBr.Net.Sat, no DEMO notei que somente o NLog de diferente, porém não pretendo usar o NLog... ou ele é necessário?

Obrigado desde já, abraço

**Comment by rftd** [comment]
NLog não é necessario.
Qual o sat que você esta utilizando, se for emulador(Cdecl) checa se o usuario tem permissão para acessar a dll do Sat.

**Comment by marcosgerene** [comment]
Sim, estou usando o emulador.

Permissão via Windows?

**Comment by rftd** [comment]
Sim é preciso ter acesso ao local onde se encontra a dll

**Comment by marcosgerene** [comment]
Adicionei um app.manifest e fiz o sistema ser requerir permissão de administrador, rodei o VS como admin também e não obtive êxito... Como devo liberar esta permissão?

Vale lembrar que o Demo funciona, deve ser algo referente a configuração, mas infelizmente não consigo encontrar =/

A pasta do DLL é a padrão do demo C:\SAT\SAT.dll

PS: Rodei o Demo sem mudar uma virgula, apenas compilei e funcionou

**Comment by marcosgerene** [comment]
Achei a solução [Neste Post](https://social.msdn.microsoft.com/Forums/en-US/d231b307-48ec-4154-a4fe-956887687847/calling-an-unmanaged-c-dll-from-c?forum=csharplanguage)

> That could be the issue. Any CPU typically will tell the runtime to JIT compile your code into a 64-bit process on a 64-bit machine. A 64-bit process is not able to load any 32-bit dlls. Try setting the target of your C# solution to x86 

Ou traduzindo, aplicações 64bits não podem carregar Dlls 32bits (x86). Simplesmente mudei nas configurações do sistema o Plataform target de AnyCPU para x86
![solucao](https://cloud.githubusercontent.com/assets/15945003/15690678/0f36e614-275b-11e6-8be8-e070df1f5831.png)

**Comment by rftd** [comment]
Sim a maioria das Dll dos sat são apenas em x86 então tem que colocar a aplicação para ser x86.
