### ISSUE TITLE
Qual impressora usar pra imprimir o cupom?

### ISSUE THREAD

**Issue by wesleycosta** [ACBrNet/ACBr.Net.Sat#51]
Boa tarde!
Quando eu mando imprimir o cupom na impressora térmica Daruma dr 700 que tenho aqui, o extrato sai meio "desformatado" sem o QrCode e o código de barras (veja imagem).
![cupom](https://user-images.githubusercontent.com/3426975/29379483-02a51d72-8299-11e7-817d-e848126dca10.jpg)

A minha duvida é a seguinte qual impressora usar pra imprimir o cupom? com essa impressora que eu tenho é possível?

Muito obrigado pela atenção... 👍

**Comment by rftd** [comment]
Sim é possível mas você precisar instalar a mesma em modo gráfico.

**Comment by wesleycosta** [comment]
Opa, agora pegou !!!
valeu 👍 

![cupom_edited](https://user-images.githubusercontent.com/3426975/29381593-21daa0a2-82a0-11e7-99ba-3959e14412ec.jpg)
