### ISSUE TITLE
Processo MF-e VP-e

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#52]
Qual processo devo seguir no appTeste?

No manual diz

EnviarPagamento
VerificarStatusValidador

EnviarDadosVenda

EnviarRespostaFiscal

No app Teste eu faço o seguinte
chave acesso ao validador que achei no google groups sobre o integrador 25CFE38D-3B92-46C0-91CA-CFF751A82D3D (futuramente a mesma sera disponibilizada pela sefaz, mas hoje acho que qualquer uuid e aceito)

1 - GeroVenda
2- inicializar
3 - MFE Enviar Pagamento

Retorno passo 3
[passo3.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/1251780/passo3.txt)

4 - Verificar Status Validador Passando como parametro o valor "2004307" retornado pelo passo 3

[passo4.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/1251782/passo4.txt)

5 - Resposta Fiscal Passando como parametro 0 retornado pelo passo 4 é a chave de acesso

[passo5.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/1251785/passo5.txt)

Ai queria informação sobre onde to errando, obrigado

**Comment by marcosgerene** [comment]
O pagamento no passo 4 ainda não esta completo, quando vc fica sem conexao (que é qdo acontece o retorno daquela forma do passo 3) vc tem que posteriormente enviar de novo o pagamento, depois enviar o status do pagamento e por ultimo a resposta fiscal.

O VerificaStatus() so vai funcionar quando você tiver internet no EnviarPagamento e o pagamento já tiver sido efetuado no POS.

**Comment by robertorp** [comment]
Tava lendo aqui, e vi o simulador POS
ai surgiu outro problema o POS retorna isso  {"status":"OK","request_id":2005286} 

O POS da vida real retorna oque equivalente ao request_id? Agora oque ta pegando e isso

**Comment by marcosgerene** [comment]
Apos feito o processo no simulador você tem que executar o verificastatus() é o resultado dele que você tem que pegar

**Comment by robertorp** [comment]
entendi mas o request_id.. de onde ele vem? da maquina? porque seto o {"status":"OK","request_id":2005286} request_id pro verificastatus() ... então o POS tem que retornar ele ne? seria o autorização?

**Comment by robertorp** [comment]
Solução: http://www.projetoacbr.com.br/forum/topic/38486-retorno-integrador-queue-item-1997815-not-complete/?sortby=date
