### ISSUE TITLE
MF-e Se a venda for cancelada? ou Se a venda der alguma rejeição?  

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#53]
Digo, Realizo um EnviarPagamento e VerificarStatusValidador
 
no processo o pdv na sequencia enviou a cf-e pra sefaz.. mas deu rejeição né... 
poxa.. resolvi cancelar o cf-e
 
e agora? oque ocorre com o enviarpagamento é verificarstatusvalidador que foi utilizado?
 
No meu sistema hoje atuo assim, a pessoa tenta enviar um sat/nfc-e se der por exemplo rejeição de cfop inválido, a pessoa pode simplesmente cancelar a venda corrente. Se isso de EnviarPagamento e VerificarStatusValidador tiver validadde juridica e não ouver uma maneira de cancelar isso, logo então vou barrar a possibilidade de de cancelar para o ceará somente e claro.

**Comment by marcosgerene** [comment]
No meu pdv eu so uso o EnviarStatus pagamento no momento da finalização da venda, logo seria quando o cartão do cliente já está na mão do caixa e a venda em si já está concluída, so falta o documento fiscal para finalizar e permitir exportar ao servidor.

**Comment by robertorp** [comment]
No meu pdv vai ser assim também, somente no momento em que clica para finalizar, mas mesmo assim, na hora de transmitir o cliente tem chance de mandar um cfop inválido com o cst/csosn (não validamos essas coisas pois contador pode pedir para colocar algo inválido, ai preferimos deixar a rejeição vir)

Supondo no processo de um método soh..

EnviaStatus
Verificarstatus
EnviaCF-e (da falha de CFOP)
Resposta Fiscal mesmo assim? ou ignoro e deixo pra lá?

**Comment by robertorp** [comment]
Me disseram que não preciso me preocupar com isso.
http://www.projetoacbr.com.br/forum/topic/38515-se-a-venda-for-cancelada-ou-se-a-venda-der-alguma-rejei%C3%A7%C3%A3o-%C2%A0/
