### ISSUE TITLE
MF-e Quando dar queue como ser tratado?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#54]
Na teoria, o POS vai se comunicar com o servidor do SEFAZ para fazer esse cruzamento, ai seu aplicativo vai receber o retorno, com os dados enviados pelo POS ao servidor do SEFAZ.

Não sei como vc fez com o simulador, mas os passos corretos são:

-enviapagamento,

-abre simulador e cola no numero serial o serial aleatório que vc enviou no enviapagamento,

-clica em 1-VFP-e,depois em 2-Pagar

-Volte no seu aplicativo e faça o verificastatus,

-emita o CF-e

-envie a respostafiscal com a chave de acesso do CF-e e armazena o IDrespostafiscal no banco de dados.

Um detalhe que vale avisar, durante a homologação, foi forçado que houvesse o retorno "queue", isto é, o integrador não conseguiu verificar o retorno do POS, o que pode acontecer na prática, e nesse caso deve ser mostrada na tela uma janela com os dados para o usuário digitar, sendo o NSU, Qtd de parcelas e Bandeira são obrigatórios. Com esses dados digitados pelo usuário prossegue a impressão do CF-e e respostafiscal normalmente.
fonte: http://www.projetoacbr.com.br/forum/topic/38486-retorno-integrador-queue-item-1997815-not-complete/?sortby=date

OK ate aqui perfeito. 
O erro pode ocorrer no verificar status pagamento correto? 

OK supondo que deu o erro, então vou obrigado a informar o NSU qtd de parcelas e bandeira e demais dados opcionais em teoria. Bom esses métodos somente se encontram no método EnviarStatusPagamento que em teoria e pra ser usado com TEF e não POS, mas como utilizo POS vou informa-los de boa sem dar problemas? Ou posso chamar o verificar status novamente? Ou simplesmente chamo diretamente o resposta fiscal?

**Comment by robertorp** [comment]
Vou homologar o meu sistema dia 05.. vamos ver oque vão pedir para ajustar e tal.
Ai vou postar aqui o resultado e como ficou tudo.

**Comment by rftd** [comment]
o @marcosgerene já fez a homologação, que eu saiba, qualquer coisa fala com ele.

**Comment by marcosgerene** [comment]
A homologação é bem tranquila, o que foi feito no componente já atende todas as exigencias... mas para ser sincero o projeto em si é uma bagunça, tem coisas que mesmo depois de 30 explicações e ler todas as notas e foruns disponíveis continuam confusas...

**Comment by rftd** [comment]
@robertorp  e @marcosgerene se estiver tudo funcionando com o MFe favor me avisar para eu fazer um release

**Comment by robertorp** [comment]
Esta funcionando perfeitamente. Minha homologação é depois de amanhã hehe

**Comment by marcosgerene** [comment]
@rftd sim, comigo está ok, não tenho ninguém em produção ainda, mas a homologação foi ok e meus testes também

**Comment by rftd** [comment]
obrigado @marcosgerene e @robertorp vou aguardar a homologação do roberto para fazer o release então, assim se mudou algo neste meio tempo fazemos as modificações antes.

**Comment by robertorp** [comment]
Feito a homologação! 
Unica ressalva que deixo aqui e a opinião de vocês se devemos implementar no componente sim ou não

Verificação se o Integrador está ativo (soltaria um AcbrException dizendo que o mesmo não esta ativo)
Deletar os arquivos da pasta Input configurada no componente se o Integrador não estiver ativo

Bom é isso. 

@rftd  @marcosgerene

**Comment by marcosgerene** [comment]
excelente!
