### ISSUE TITLE
NullPointer ao tentar imprimir sem ter impressora

### ISSUE THREAD

**Issue by FernandoTBarros** [ACBrNet/ACBr.Net.Sat#55]
![image](https://user-images.githubusercontent.com/3437672/30006710-0c1038fc-90d5-11e7-9712-b018a5dda241.png)
A variável Extrato estava null. Acho que o correto talvez seria:
``
Guard.Against<ArgumentNullException>(Extrato == null, "Componente de Impressão não definido !");
``

**Comment by rftd** [comment]
Se a variável esta nula foi por que você não adicionou nenhum componente de impressão.

**Comment by FernandoTBarros** [comment]
Sim, não havia adicionado. Porém pelo que eu entendi dessa linha ele estava tratando justamente se a variável Extrato estava nula ou não, mas deu nullPointer justamente ao tentar acessar Extrato para perguntar se ela estava null. 
Ou estou entendendo errado ?
