### ISSUE TITLE
Erro ao imprimir - O sistema X parou de funcionar

### ISSUE THREAD

**Issue by wesleycosta** [ACBrNet/ACBr.Net.Sat#56]
Bom dia, estou com uma dificuldade de impressão!

Então vamos lá, a minha dificuldade é a seguinte, quando eu faço a 1ª venda pelo meu PDV funciona perfeitamente e o sistema imprime o cupom (veja a imagem a baixo)

![captura de tela 104](https://user-images.githubusercontent.com/3426975/30275257-217df686-96d7-11e7-95b9-dd2aaab253d3.png)

Entretanto quando faço a 2ª venda o sistema gera o cupom e aparece na tela igual a img acima, porém quando fecho a tela de pré-visualização do cupom o sistema apresenta o seguinte erro:

![captura de tela 105](https://user-images.githubusercontent.com/3426975/30275318-55f139c8-96d7-11e7-805d-aded4107377a.png)

Trecho de código para gerar e imprimir o cf-e:
![captura de tela 102](https://user-images.githubusercontent.com/3426975/30275525-01557072-96d8-11e7-9995-051d15c7cba6.png)
![captura de tela 103](https://user-images.githubusercontent.com/3426975/30275526-015b6284-96d8-11e7-915b-f9ea1921eb9a.png)

Já tentei instalar e desinstalar o FastReport demo, porem não pegou.
Se eu comentar a chamada do método ImprimirExtratoCompleto() o sistema roda sem apresentar o erro acima (claro e sem imprimir o extrato tbm :D)

Agradeço pela atenção.

**Comment by rftd** [comment]
Qual erro aparece no Debug ?

**Comment by wesleycosta** [comment]
Então não estou conseguindo debugar, no meio do debug aparece esse erro:

![captura de tela 111](https://user-images.githubusercontent.com/3426975/30397430-464db8fc-98a3-11e7-9682-5794916ad25a.png)


Geralmente esse erro aparece quando eu estou na linha 112:
![captura de tela 112](https://user-images.githubusercontent.com/3426975/30397401-30200c60-98a3-11e7-9853-5f84a76fafbe.png)

Porém esse erro só acontece quando uso pré-visualização, se eu mandar direto pra impressora funciona normal.

**Comment by wesleycosta** [comment]
@

**Comment by rftd** [comment]
neste caso não tenho muito o que ajudar pois é uma função interna do FastReport, pode ser bug da versão do FastReport tente trocar a versão por outra mais antiga ou mais atual.

**Comment by wesleycosta** [comment]
Blz, vou instalar outras versão do FastReport, se eu encontrar a solução posto aqui.

Agradeço pela atenção.
