### ISSUE TITLE
[SAT] - Multiplos caixas

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#59]
Salve @rftd,

Abri a issue pra gente ter isso documentado.

Um cliente quer usar 2 caixas compartilhando o mesmo SAT, eu já fiz isso uma vez em Delphi + ACBr mas controlando tudo no meu software, gravava no banco, controlava uma fila com um "processador de SAT", etc.

Eu queria fazer algo nesse sentido no componente, tenho certeza que mais gente precisaria disso, o que acha da ideia? Estou aberto à sugestões de como nós poderíamos implementar isso....

PS: neste meu cliente o volume é pequeno, provavelmente um único caixa seria mais que o suficiente, existe dois caixas lá pela estrutura física do negócio, o local é muito largo, é como se fosse duas lojas, de um lado atende-se os consumidores menor e do outro é aonde são atendidos as empresas

Abraço

**Comment by marcosgerene** [comment]
**Ideia 1:**
Lado cliente:
Gerar o xml de envio normalmente na pasta envio, mas com um nome que viesse de um Guid (uuid) e esperasse o retorno desse uuid na pasta "emitidos" com um timeout de espera.

Lado servidor:
Ler os arquivos na pasta "enviados", processar eles, mover para outra pasta (para nao processar 2 vezes ou deletar) e após processar gravar o arquivo processado na pasta "emitidos".

-------

**Vantagem:**
Isto não envolveria nenhuma alteração no código já existente no componente, apenas a criação de um "Demo" que faça isso para facilitar implementações futuras;

**Desvantagem:**
Depende de compartilhar pastas na rede e ceder permissões;

------

Sim, a "inspiração" foi o integrador do CE rsrs

**Comment by rftd** [comment]
Rapaz mais fácil criar um serviço WCF e utilizar ele do que fazer um monitor.

**Comment by robertorp** [comment]
Estava lendo sobre isso, realmente a unica maneira de fazer é assim hehe.
Mas como @rftd disse servico WCF so que com uma diferença, utilizando troca de JSON acho massa assim =D Bom se fosse eu fazer era assim hehe. Qual o motivo do JSON? Simples se alguém quiser implementar para android é so conectar no ip/porta e zerou =D
Aqui utilizamos servicos WCF + Windows Service pra tudo no sistema que envolva algo com o server hehe.

**Comment by rftd** [comment]
Isto pode ser feito com WCF também amigo.

https://www.codeproject.com/Articles/105273/Create-RESTful-WCF-Service-API-Step-By-Step-Guide

**Comment by robertorp** [comment]
Então nos fazemos aqui na empresa assim. So que utilizamos JSON hehe porque achamos melhor so isso, e questão de gosto hehe.
![servicos](https://user-images.githubusercontent.com/10251705/31229627-bf5fbcca-a9b7-11e7-9779-c0aebb5ab3a4.png)

**Comment by rftd** [comment]
Rapaz da para fazer até numa raspberry se quiser
auhauhauhauauh

**Comment by marcosgerene** [comment]
@rftd e @robertorp com a pressa de entregar eu fiz no banco de dados uma fila entreguei funcionando, mas a ideia de fazer algo no componente segue...

**Comment by marcosgerene** [comment]
>@rftd Rapaz mais fácil criar um serviço WCF e utilizar ele do que fazer um monitor.

Qual seria o funcionamento no server e no client, explana isso... enviar o xml no client e esperar o server processar e pegar o xml de resosta? Explana melhor o que pensa sobre isso...

>@robertorp ... Json ...

Eu particularmente gosto muito de usar json,acho leve e simples, mas neste caso eu acho que mandar o xml "pronto" daria menos trabalho, pois o componente já é capaz de serializar/deserealizar ele.
