### ISSUE TITLE
Valores decimais diferentes no XML

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#6]
Os valores decimais estão corretos no objeto, porém ao gerar o XML os valores ficam sem o separador decimal (ou seja, multiplicado por 100), note no VCFe e no VCFeLei12741

Olhei no Demo e não consegui achar nenhuma configuração para isto.

Objeto prrenchido:
![objeto](https://cloud.githubusercontent.com/assets/15945003/15692370/6707677a-2764-11e6-909a-bedf9f27a1eb.png)

Geração do XML:
![xml](https://cloud.githubusercontent.com/assets/15945003/15692378/713a4384-2764-11e6-8391-f89485276de0.png)

Obs1: No demo o problema não ocorre.
Obs2: Todos os meus valores (ou quase todos) partem de uma conversão de float para decimal.

Código exemplo do meu projeto:
[preenchimento.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/292299/preenchimento.txt)

**Comment by rftd** [comment]
Não tem configuração para isto ele usa o CultureInfo.InvariantCulture.NumberFormat para gerar o valor.
Nos meus testes estão gerando os valores corretamentes.
Qual a culture padrão da sua IDE e quais as sua configurações regionais em relação a numeros.

Obs.: O Codigo de geração e leitura do XML esta na Lib DFe.Core

**Comment by marcosgerene** [comment]
Bom dia,
Baixei os dois fontes, vou compilar tudo na mesma máquina para testar, mas acho que deve ser algo referente ao projeto assim como era o target, pois nas mesmas condições (máquina e IDE) o Demo funciona.

Te retorno assim que tiver uma resposta, abraço

**Comment by marcosgerene** [comment]
@rftd , não obtive sucesso... eu "instalei" no meu projeto referenciando as DLLs, está errado isto? Devo adicionar à minha solução os projetos (Sat, Core e DFe.Core)?

**Comment by rftd** [comment]
Não precisa adicionar a solução os projetos a não ser que queira debugar para achar onde esta o problema.
O que deve estar acontecendo é que seu windows esta com uma configuração regional e o seu sistema outra.
Vou fazer uma mod na lib do DFe.Core para ver se resolve isto.

**Comment by marcosgerene** [comment]
Não deu certo, dei update, removi as referencias, apaguei as dlls, referenciei novamente e o resultado foi o mesmo (o separador decimal "some").

Vou tentar debugar, adicionei o projeto (Dfe.core e sat) à minha solução mas não consegui debugar as classes do DFe.Core, vou ver o que fiz errado, debugar e te falo o resultado

**Comment by marcosgerene** [comment]
Boa tarde,

Achei a solução... foi só setar a propriedade RemoverAcento para false (tinha deixado como true)...
o XML agora gerou com os valores ok.
Tive um outo problema (GTIN) mas meu teamviewer estava horrível para testar...

Vou fechar essa Insue porque, pelo menos para mim, o problema foi sanado só com a propriedade RemoverAcento.

Abraço
