### ISSUE TITLE
Cortar cupom automaticamente

### ISSUE THREAD

**Issue by wesleycosta** [ACBrNet/ACBr.Net.Sat#60]
Boa tarde, alguém sabe como que eu faço para cortar um cupom automaticamente apos a venda?
Agradeço pela atenção.

**Comment by AlanJovita** [comment]
Boa tarde Wesley, vc faz comunicação com a impressora através de DLL ? 

se for por dll tem que dar o comando via código vide documentação da mesma.

ou se utilizar o spooler instalado no windows pode configurar por lá mesmo nos parametros, End of doc ou  End of Page da impressora;

**Comment by marcosgerene** [comment]
@wesleycosta outra opção é enviar um comando de corte em escpos para a impressora, eu faço isso, ja peguei casos, principalmente com a elgin i9 que a guilhotina não acionava ou acionava no momento errado, entao tirei o corte e fiz cortar via escpos

**Comment by wesleycosta** [comment]
Bom dia galera, primeiramente agradeço pela ajuda de todos vou tentar cortar aqui da duas maneiras usando o spooler instalado no windows e com escpos...

Com escpos eu já estava tentando porém não estou conseguindo, já tentei usar a classe RawPrinterHelper para enviar o comando mas não consegui...

@marcosgerene como que vc fez para enviar um comando escpos, poderia por favor compartilhar o trecho de código?

**Comment by marcosgerene** [comment]
@wesleycosta utilizo a classe RawPrinterHelper como vc mesmo disse.

```
        public static void CortarPapel(string impressora, string bytesCorte)
        {
            var comando = bytesCorte.Split(','); //Elgin i9 -> 29,86,0
            int[] cut = new int[comando.Length];
            for (int i = 0; i < comando.Length; i++)
                cut[i] = int.Parse(comando[i]);
            
            RawPrinterHelper.SendBytesToPrinter(impressora, intTobyte(cut));
        }
```

Chamando na elgin i9.

```
ImprimirSat();
CortarPapel(nome_da_impressoa, "29,86,0");
```

**Comment by wesleycosta** [comment]
Opá agora pegou!
Obrigado @marcosgerene e @AlanJovita!
