### ISSUE TITLE
Erro Serializar a propriedade CFe - InfCfe no metodo GetXml

### ISSUE THREAD

**Issue by jrvilareal2017** [ACBrNet/ACBr.Net.Sat#61]
Boa Tarde.

Este erro acontece qdo dentro do método EnviarDadosVenda, a função GetXml é chamada. Segue o erro abaixo.

Erro: Erro ao serializar a propriedade:\r\nCFe - InfCFe

Consegui resolver o problema voltando para versões anteriores do acbrsat, acbrsar dfe e core.

Alguém conseguiu resolver o problema usando as versões novas do acbrsat e dfe e core ?

**Comment by rftd** [comment]
Não consegui reproduzir seu erro com a versão mais nova do ACBrSat e nem com a versão de desenvolvimento.

**Comment by jrvilareal2017** [comment]
Bom dia, fiz teste com as versões novas da dll, todos as vezes que tento enviar um cupom, seja de venda, o testefimafim, ocorre o erro acima descrito. Segue uma imagem com o erro. Poderia me passar o e-mail para enviar o projeto console de teste com o erro.

![image](https://user-images.githubusercontent.com/33378909/32438765-da30d618-c2d2-11e7-83aa-bb7fc7747da1.png)


Obrigado.

**Comment by rftd** [comment]
eu baixei o seu projeto no acbr e não consegui reproduzir o erro, baixe novamente o repositorio e tente noamente.

**Comment by jrvilareal2017** [comment]
Boa noite, baixei o projeto novo aqui no github, no demo tudo normal, carrega um xml e consigo usar o getXml normalmente. Criei um novo projeto console, carregando o xml gerado pelo Demo, Método load, normal, qdo executo o cfe.GetXml, mesmo erro acontece, Erro ao serializar o objeto. Obs: Referência realizada através do NuGet, e as mesmas foram atualizadas:

Exemplo de código que acontece o erro:

            var cfe = CFe.Load(@"C:\Users\Raphael\Desktop\ConsoleApplication1\ConsoleApplication1\AD20171031182439-692660-env.xml");
            try
            {
                var teste = cfe.GetXml();
            }
            catch(Exception ex)
            {
               Console.WriteLine(ex.Message);
            }

**Comment by marcosgerene** [comment]
Por favor, anexe o XML que causa este exception.

Eu uso essa biblioteca em produção a um bom tempo e nunca tive problemas... Att, Marcos

**Comment by jrvilareal2017** [comment]
Bom dia Marcos.

Segue em anexo o Xml que ocorre o erro.

[AD20171031182439-692660-env.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/1470445/AD20171031182439-692660-env.zip)

Logo abaixo o projeto console com erro:

[ConsoleApplication1.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/1470447/ConsoleApplication1.zip)


Obrigado.

**Comment by marcosgerene** [comment]
Baixei sua aplicação e apenas troquei as referencias pelas dlls que compilei (sem mexer no fonte) e funcionou, acredito que sua versão esteja defasada.

![getxml](https://user-images.githubusercontent.com/15945003/32778258-5f2bbd6c-c920-11e7-9354-e2ee5a8b7f8b.gif)

PS: o erro realmente acontecia antes de eu trocar as refencias

**Comment by jrvilareal2017** [comment]
Marcos eu referenciei pelo NuGet e mandei atualizar estava mostrando a ultima versão.

Vlw.

**Comment by marcosgerene** [comment]
@jrvilareal2017 se o problema foi solucionado feche a issue, por favor.

**Comment by jrvilareal2017** [comment]
Marcos, realmente, peguei as dll da pasta do demo e referenciei no meu projeto console e deu certo.

Só que a versão que esta no NuGet, não, se começar um projeto e referenciar pelo mesmo, da erro.

Vlw.

**Comment by rftd** [comment]
Qual a versão do nuget esta com erro ?

**Comment by jrvilareal2017** [comment]
Bom dia, com essas referências, ocorre o erro:

Acbr.Net.Core           1.0.1.8
Acbr.Net.Dfe.Core     1.0.2.4
Acbr.Net.Sat              1.0.1.5

**Comment by jrvilareal2017** [comment]
Boa noite, as versões das dll do NuGet e da dll da pasta Bin do projeto demo estão diferentes, pois a classe CodigosSat não é encontrada qdo estou referenciando pelo NuGet, somente pela Dll da pasta Bin, ou eu estou fazendo algo errado.

**Comment by rftd** [comment]
a demo é a versão que esta atualmente em desenvolvimento, por isso tem diferenças
eu devo fazer um release esta semana ainda no nuget.

**Comment by jrvilareal2017** [comment]
Bom dia, tudo bem rafael, vlw.
