### ISSUE TITLE
[ACBr S@T C#] Erro ao criar "CfgArquivos"

### ISSUE THREAD

**Issue by gabrielmarinhoct** [ACBrNet/ACBr.Net.Sat#62]
Bom dia pessoal...
Dei uma pesquisada sobre minha dúvida mas não achei algo.

É o seguinte:

Estou usando o ACBrSat para C# e ao dar "new" na classe ACBrSat da erro na criação da classe "CfgArquivos" ao executar o comando "Assembly.GetEntryAssembly().GetPath();", retorna null.

Alguém passou por algo parecido?

Para resolver, pelo menos temporariamente, baixei o projeto do ACBr no github, inclui na minha solution e alterei a linha em questão. Mas isso poderá "me complicar" em uma atualização futura do ACBr.

 

Agradeço a atenção
Abraço

**Comment by rftd** [comment]
Qual ambiente que você esta usando ?

**Comment by gabrielmarinhoct** [comment]
É um PDV web. Mas a ideia é ter o MonitorACBr em um servidor acessando o S@T.
Estamos utilizando no front AngularJS que enviará para o back-end em C#, dados para o S@T.

Obrigado
Abraço

**Comment by rftd** [comment]
A biblioteca não foi feita pensando web devido ao fato de necessitar usar comunicação USB ela é feita para ser usada direto para comunicação com Sat.
Com ela não precisa do ACBrMonitor é so usar ela para comunicação e com o monitor não precisa dela.
