### ISSUE TITLE
CFeDetProd ->  det.Prod.VUnCom  com 2 casas Decimais da ERRO

### ISSUE THREAD

**Issue by trajanojunior** [ACBrNet/ACBr.Net.Sat#63]
[TesteFimAFim_755209_Com2CasasDec.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/1523923/TesteFimAFim_755209_Com2CasasDec.zip)
[#TesteFimAFim_540391_Com3CasasDec.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/1523924/TesteFimAFim_540391_Com3CasasDec.zip)

Ola,
Amigos,
goataria de comunicar, que,
*** Situação ***
Qnd se cria um CFe,
no DetProd  o campo valor Unitario Com, (VunCom)
esta com 2 casas decimais.
ao gerar o xml e enviar para o integrar , não passa, o xml eh rejeitado.
*** Solução ***
Depois de muito procurar solucionei colocando 3 casas decimais,
ai passou.

Espero ter contribuído com o Grupo.
Att.
Junior Trajano

**Comment by rftd** [comment]
Você deve estar vendendo combustivel então por que so assim pode ser 3 casas decimais e neste caso é so setar a propriedade EhCombustivel como true.

![sem titulo](https://user-images.githubusercontent.com/299476/33517460-6408edd6-d763-11e7-815b-7481b0aaf2a1.png)

**Comment by trajanojunior** [comment]
Ok,
Valeww.
