### ISSUE TITLE
Maturidade do projeto ACBR.Net.Sat

### ISSUE THREAD

**Issue by apbertoletti** [ACBrNet/ACBr.Net.Sat#65]
Olá pessoal, td bem?

Poderiam me informar se este componente do ACBR.Net.Sat já esta em uso comercialmente por alguma software house, e como está sendo a experiência dos prós e contras neste aspecto.

Pergunto isso, pois estamos avaliando diversos componentes do mercado a fim de implementarmos uma solução SAT para nossos clientes.

Muito obrigado

André

**Comment by marcosgerene** [comment]
@apbertoletti uso o projeto em pelo uns 30 clientes em produção a mais ou menos 1 ano.

O @robertorp usa em produção também, agora não sei a quantidade de clientes.

O projeto tem poucas alterações porque o SAT exige pouquíssima manutenção, o maior "problema" do projeto seria a parte de impressão que só tem em FastReports, mas isso pode ser contornado com outra ferramenta.

**Comment by robertorp** [comment]
Utilizo para Modulo fiscal eletronico do ceará, e SAT , nunca tive problemas com o componente em si. Revemos umas 4 revendas em SP que instalam SAT. E no ceará temos 2 revendas vendendo MF-e. Utilizo para impressão em ambos o ACBRMonitor. Motivo cheio de parametros para tamanhos essas coisas.

Nosso sistema: releases.sistemafusion.com.br
sistemafusion.com.br

**Comment by marcosgerene** [comment]
Acredito que esta issue https://github.com/ACBrNet/ACBr.Net.Sat/issues/66 resolve nosso problema com impressão, ainda não vi o código, mas se funcionar o "calcanhar de aquiles" do projeto morre

**Comment by apbertoletti** [comment]
Obrigado pelos feedbacks pessoal,

vamos iniciar os estudos deste projeto por aqui.

abraços.
