### ISSUE TITLE
Erro ao Ativar utilizando Sat Demo.

### ISSUE THREAD

**Issue by eduferrari32** [ACBrNet/ACBr.Net.Sat#67]
Olá, estou tentando realizar testes com a ferramente disponibilizada e ao tentar utilizar a opção "ativar SAT" ou qualquer outra opção (Teste Fim a Fim - Enviar Venda, etc etc)  ocorre uma exceção que não consigo identificar o por que. Alguém poderia me ajudar ?

Exceção Retornada ( Managed Debugging Assistant 'PInvokeStackImbalance' 
  Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'ACBr.Net.Sat!ACBr.Net.Sat.SatStdCall+Delegates+AtivarSAT::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
)

![image](https://user-images.githubusercontent.com/35135526/34605154-a070f108-f1f1-11e7-880a-0b869028e0ba.png) <- Imagem do Método que apresenta o erro no compilador.

![image](https://user-images.githubusercontent.com/35135526/34605175-bf30926a-f1f1-11e7-9507-7af5d82d1ef1.png) <- Imagem do Emulador SAT logo após o erro.

Desde de já agradeço.

**Comment by rftd** [comment]
Você esta utilizando a opção StdCall e a dll do emulador é cdecl.

**Comment by eduferrari32** [comment]
Opa, deu certo cara obrigado. 
Porém tenho outra questão.. assim que eu tento fazer uma ação por exemplo, criar uma venda e enviar a mesma ocorre um erro no emulador, como se eu informasse um campo e ele estivesse null, o layout do xml criado é o mais atual disponivel?

Veja tela com o Erro no emulador.

![image](https://user-images.githubusercontent.com/35135526/34622215-6c799a16-f233-11e7-83d5-d674aaf39bb9.png)

**Comment by rftd** [comment]
Você deve estar preenchendo algo errado nos dados do emissor da CFe por isso esta ocorrendo este erro.
