### ISSUE TITLE
Duvida desconto CFe SAT

### ISSUE THREAD

**Issue by AlanJovita** [ACBrNet/ACBr.Net.Sat#68]
Bom dia pessoal,

estou com um problema que descobri no final de semana em um cliente.
o valor de desconto está debitando duas vezes no calculo da CFe conforme imagem. E se o valor do desconto for maior que 50% dá erro pois a conta não fecha.

![cfedesc](https://user-images.githubusercontent.com/30324990/34722691-f60e1ab0-f52e-11e7-9fab-757eeb9e19ac.jpeg)

será que estou preenchendo corretamente o objeto ?

```
 Dim det = CfeAtual.InfCFe.Det.AddNew()
                det.NItem = 1 + i 'Sequencia numerica para o item
                det.Prod.CProd = Prod.codigo
                det.Prod.CEAN = Prod.codigo_barras
                det.Prod.XProd = Prod.descricao
                det.Prod.NCM = Prod.ncm
                det.Prod.CFOP = CFOP.cfop1
                det.Prod.UCom = If(Prod.unidade, "und")
                det.Prod.QCom = Prod.quantidade
                det.Prod.VUnCom = CDec(Prod.preco_venda)
                det.Prod.VDesc = IIf(IsNothing(Prod.item_desconto), 0, (Prod.item_desconto * Prod.quantidade)) 'Desconto sobre o item
                det.Prod.VOutro = IIf(IsNothing(Prod.item_adicional), 0, (Prod.item_adicional * Prod.quantidade)) 'Acrescimo sobre o item

                det.Prod.IndRegra = IndRegra.Truncamento
                CfeAtual.InfCFe.Total.DescAcrEntr.VDescSubtot += det.Prod.VDesc
                CfeAtual.InfCFe.Total.DescAcrEntr.VAcresSubtot += det.Prod.VOutro
```

**Comment by rftd** [comment]
1. Trucamento apenas posto de combustíveis, todos os outros apenas arredondamento.
2. A sua impressão esta incorreta, no total Bruto não vai desconto.
3. No Sat não pode ter desconto e acréscimo ou tem 1 ou outro.

**Comment by AlanJovita** [comment]
Perfeito @rftd 

Fiz a alteração no IndRegra e Total bruto, se possível atualize por favor na impressão que disponibilizei na #66 que está incorreto.

entre desconto e acréscimo eu já faço o tratamento antes com a diferença diretamente no AC.

porem ainda não estou conseguindo entender o calculo do `Cfe.InfCFe.Total.VCFe` ele continua zerando o pedido igual a imagem acima descontando duas vezes.

no total da impressão eu passo somente o `Cfe.InfCFe.Total.VCFe` .

**Comment by rftd** [comment]
Cfe.InfCFe.Total.VCFe é preenchido pelo Sat ele que é reponsavel por preencher esta tag, confira a xml retornada pelo sat para ver se a tag vem preenchida.
E sobre o projeto de impressão Nativo ele é interessante mais não esta no padrão do ACBrSat e a impressão também não esta de acordo com o manual do Sat, mas eu estou mexendo em um impressão nativa no meu tempo livre.

**Comment by rpotalara** [comment]
@rftd Rafael, sobre a impressão do cupom sat nativo, o que exatamente acredita que não esta de acordo com o manual? O que pude observar somente é que esta sendo usado o layout do cupom de 5,5cm no de 8cm, seria isso? Obrigado.

**Comment by rftd** [comment]
1. Não preve se esta em homologação e por isso não imprime as linhas de homologação e não deixa o numéro do extrato zerado.
2. Esta imprimindo a parte dos imposto incorreto, esta igual no NFCe e não é.

De cabeça lembro estes, mas tem mais coisas, sem falar que ele não calcula direito se o texto vai caber no cabeçalho corretamente e não da opção de imprimir logo.

Se quiser discutir o assunto por favor continue no issue sobre a impressão #66.
