### ISSUE TITLE
TAG vTroco devo informar ela ou não ?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#69]
O MF-e pelo que vi na tag vTroco não devo informar ela, o próprio mf-e calcula a tag vTroco

Mas a Tanca simplesmente deve ignorar isso, e aceitou de boa. 
Mas a Elgin não aceitou. 

Conclusão no MF-e não devo informar a vTroco.

Agora queria saber se a vTroco no SAT de São Paulo eu devo informar a tag vTroco sim ou não.

Foto do que diz no manual

![vtroco](https://user-images.githubusercontent.com/10251705/35165219-9abc3b48-fd34-11e7-89d8-2bb5abadd1e4.png)

**Comment by apbertoletti** [comment]
Olá Roberto, 

Eu entendo o seguinte: se no manual tá dizendo que o calculo do troco é por conta do SAT, então o seu software não precisa passa-lo.

Ajudei?

**Comment by rftd** [comment]
como @apbertoletti disse segundo o manual Sat quem deve calcular o troco é o aparelho ou seja você não deve informar esta tag.

Isso parece ser bug do Software do Sat Elgin, a bematech também tem uns bugs estranho desse.

**Comment by robertorp** [comment]
Verifiquei também que tudo oque começa com SAT na primeira coluna e feito pelo próprio sat isso serve de referencia para min. Realmente foi falta de atenção minha já tava biruta rsrs, li o texto 1000 vezes e não li "Cálculado pelo SAT"  eu li "Cálculo (x -x * Y etc.. kk)" obrigado.

**Comment by rftd** [comment]
Sim todas a tags que tem a linha iniciada com SAT são linha preenchidas pelo aparelho e as com AC por você.
