### ISSUE TITLE
Erro na consulta Status operacional usando kit desenvolvimento tanca

### ISSUE THREAD

**Issue by jrvilareal2017** [ACBrNet/ACBr.Net.Sat#70]
Boa noite, realizando teste com o kit, ocorre o erro nesta linha,

Status.DhCFe = DateTime.ParseExact(RetornoLst[i], "yyyyMMddHHmmss", CultureInfo.InvariantCulture);

Pois o valor no indice i = 23 esta com zeros.

Mas qdo uso o emulador do governo funciona normalmente.

![erro consulta status operacional](https://user-images.githubusercontent.com/33378909/35461151-c08d0e1c-02cd-11e8-871a-f5e08cdb292b.jpg)

**Comment by rftd** [comment]
Erro do kit ou a string esta vindo errada entre em contato com o fabricante.

**Comment by jrvilareal2017** [comment]
Obrigado, vou entrar em contato segunda feira com a tanca.

**Comment by rftd** [comment]
tem casos que apenas trocando a dll por uma mais nova ou mais antiga resolve
pois a comunicação é toda feita pela mesma eu so faço as chamada das funções da dll.

**Comment by jrvilareal2017** [comment]
Problema solucionado com a tanca.
