### ISSUE TITLE
AccessViolationException na hora de executar o comando EnviarVenda

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#71]
AccessViolationException na hora de executar o comando EnviarVenda

SAT Elgin

alguém já passou por isso? De mais comandos funcionam normalmente, somente o EnviarVenda que estoura.

**Comment by rftd** [comment]
Muito provavelmente erro na dll do fabricante tente pegar uma versão mais atual.
Checar se tem todas as dependências.

**Comment by AlanJovita** [comment]
Se não me engano tive um erro parecido com a DIMEP

alem de confirmar as versões e dependencias! 

eu fiz o seguinte, dei as permissões "todos" para a pasta, copiei os arquivos do sat para a system32 e/ou sysWOw64.

é apenas uma dica que funcionou comigo.

**Comment by robertorp** [comment]
obrigado a todos pelas dicas,

bom minha solução foi a seguinte, 

Estrutura onde meu sistema e instalado

C:\SistemaFusion\FusionNfce

as dll do sat se encontram aqui C:\SistemaFusion\FusionNfce\SATdll\Elgin (elgin foi a que deu AccessViolationException comigo)

eu copiei a DLL zlib.dll da pasta C:\SistemaFusion\FusionNfce\SATdll\Elgin 

e colei a mesma em C:\SistemaFusion\FusionNfce

bom e tudo funcionou normalmente.. motivo? Não sei se alguém souber me explicar agradeço, pois foi um chute que fiz somente. (Lembrando que antes de fazer esse chute fiz muitos outros, copiei dll's para system 32/64 etc.. outros lugares do computador , tentei usar ela a partir da dll dentro da pasta do linker Elgin enfim tentei muitas coisas e a solução foi essa que disse.

Como ficou no final? 
Bom o caminho da dll do sat elgin ficou assim C:\SistemaFusion\FusionNfce\SATdll\Elgin\dllsat.dll

mas tive que ter uma copia da zlib.dll dentro da pasta C:\SistemaFusion\FusionNfce
eu presumi que alguma coisa na iterop quando abro o FusionNfce.EXE que fica dentro da pasta C:\SistemaFusion\FusionNfce , quando e feito o uso da dllsat.dll da elgin de alguma maneira ela pegou o caminho do EXE para acessar a zlib.dll 

Isso e somente uma suposição do que aconteceu, não sei se de fato foi isso.
