### ISSUE TITLE
MF-e layout sempre sera o mesmo que o CF-e SAT?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.Sat#73]
a duvida é, conferindo aqui o layout e futuras atualizações do layout do SAT Fiscal, como atendo MF-e também, queria saber se é o mesmo sempre para ambos afinal o MF-e nasceu do SAT

**Comment by rftd** [comment]
Que eu saiba não tem nenhuma portaria do CE que mude o layout atual do documento CFe, mas esta possibilidade pode existir sim.
