### ISSUE TITLE
Não foi possivel carregar a biblioteca.

### ISSUE THREAD

**Issue by ghost** [ACBrNet/ACBr.Net.Sat#76]
Olá... estou tentando usar o projeto demo mas sempre tenho esse erro:

```
Exception thrown: 'ACBr.Net.Core.ACBrException' in ACBr.Net.Core.dll
An unhandled exception of type 'ACBr.Net.Core.ACBrException' occurred in ACBr.Net.Core.dll
Não foi possivel carregar a biblioteca.
```

já verifiquei o caminho da dll, já troquei de any pra x64 e x86... não importa o que faça aqui o problema continua... 

para teste estou usando um SAT de Homologação Sweda... 

alguém pode me dar uma luz?

**Comment by rftd** [comment]
Você informou o caminho da dll, da Sweda, selecionou corretamente o tipo ?
Lembrando que geralmente os fabricantes usam o tipo da dll é StdCall.

**Comment by ghost** [comment]
Obrigado por responder...

>  Você informou o caminho da dll, da Sweda, selecionou corretamente o tipo ?

Sim, mas se informo por exemplo C:\SAT\SATDLL.dll continua dando erro...
mas se gero o ACBr.Net.Sat.Demo.exe e coloco a dll na mesma pasta do exe e no campo nome da dll informo somente SATDLL.dll ai da certo...

> Lembrando que geralmente os fabricantes usam o tipo da dll é StdCall.

Sim, estou usando StdCall

**Comment by rftd** [comment]
então neste caso é permissão de acesso do windows, ele não esta conseguindo acessar o path.

**Comment by ghost** [comment]
era isso mesmo! problema resolvido.. obrigado pela atenção!!!
