### ISSUE TITLE
Como associar componente de impressão?

### ISSUE THREAD

**Issue by ghost** [ACBrNet/ACBr.Net.Sat#77]
Pessoal me desculpem por essa pergunta, estou iniciando agora com C# ainda estou um pouco perdido...

mas como faço para associar o componente de impressão para  imprimir o extrato fiscal pelo ACBr.Net.Sat.Demo? Vi que tem o ACBr.Net.Sat.Extrato.FastReport... mas não consegui encontrar um exemplo de como associar...

**Comment by marcosgerene** [comment]
Os projetos são "independentes" (na verdade o Extrato usa o ACBr.Net.Sat), ou seja, não existe a associação dos componentes como acontece no ACBr "normal" (Delphi). O projeto do extrato tem um demo próprio, veja nele o funcionamento da impressão, é mais fácil para entender.

**Comment by ghost** [comment]
Olá Marcos! obrigado por responder....

ok entendi... consegui fazer o teste aqui, deu tudo certo!
