### ISSUE TITLE
Comunicação Software e Hardware S@T

### ISSUE THREAD

**Issue by eduferrari32** [ACBrNet/ACBr.Net.Sat#78]
Boa tarde,

Estou utilizando a dll ACBr.Net.Sat para desenvolvimento de um software com o modulo de venda S@T, ja fiz os testes possíveis com o emulador e todos correram bem. Porém agora na fase de testes com o hardware não consigo obter comunicação da maquina ( Bematech  RB-1000) com o meu software, gostaria de saber se existe alguma configuração que deve ser feita para realizar esta ponte de comunicação com o hardware através da dll ACBr.Net.Sat .

**Comment by rftd** [comment]
Você precisa apensa setar o path correto da dll da bematech e configurar o calling convention correto no caso da bematech é stdcall.

**Comment by eduferrari32** [comment]
Sim esta parte esta toda correta, ao montar todo o Cfe e no método EnviarDadosVenda o debug entra no processo e ai não obtenho resposta... Fica somente processando e sem retorno nenhum.

**Comment by eduferrari32** [comment]
Existe um arquivo dentro da pasta C:\SAT com o nome configuracoes.xml , este arquivo é somente para emulador ou ele é usado na comunicação com o Hardware do sat também ? Aproposito outra informação, usamos o projeto disponibilizado aqui no GitHub para realizar o mesmo teste e também não obtemos êxito na comunicação com o hardware.

**Comment by rftd** [comment]
Cara esta pasta C:\Sat é apenas para o emulador a dll dai não serve para o aparelho, você precisa baixar o driver da bematech instalar e la dentro vai ter a dll da bematech, a bematech usa um ini para configurar as coisas.

**Comment by eduferrari32** [comment]
Obrigado cara, não sabia desta informação, eu apontei pra DLL da Bematech, configurei o arquivo para apontar a porta onde esta instalado o hardware e etc. Porém me retornou outro erro, dessa vez originado da DLL da ACBr, tanto no programa de teste disponibilizado quanto no meu software. Será que falta informar algum outro parâmetro para o processo da DLL? Consegue me ajudar a respeito desse erro por favor? Segue imagem em anexo do erro retornado pelo programa de testes disponibilizado aqui.

![image](https://user-images.githubusercontent.com/35135526/43148736-4b14d0c4-8f3c-11e8-8157-e3ba0b6b6d6d.png)

**Comment by rftd** [comment]
qual modelo você esta usando na dll do emulador era Cdecl na dll da Bematech tem que ser StdCall.

**Comment by eduferrari32** [comment]
estou usando StdCall.

![image](https://user-images.githubusercontent.com/35135526/43151393-417238da-8f42-11e8-8fde-7f2387b6c6d3.png)

**Comment by rftd** [comment]
então o problema é o acesso ao path onde esta a dll, outra coisa o demo é 32 bits e pela imagem esta usando a dll 64 bits ai também não vai funcionar.

**Comment by eduferrari32** [comment]
Boa tarde, era isso mesmo cara, precisava da DLL 32bits.. Vou continuar os testes, muito obrigado pela força !
