### ISSUE TITLE
Erro 6010 - Erro validação do conteúdo SAT

### ISSUE THREAD

**Issue by eduferrari32** [ACBrNet/ACBr.Net.Sat#79]
Bom dia,

Ao tentar realizar o envio de uma CFe estou obtendo o retorno do Hardware Bematech, "6010 - Erro validação do conteúdo", fiz a extração do log de erro da Bematech e o mesmo aponta erro nas tags 'xNome' e 'Versao'. A impressão que dá é que existe algo errado com a versão do xml criado através do programa, gostaria de confirmar se é este o possível problema, e se existe alguma atualização das dll's para geração do layout mais atual. 

Trecho do log bematech extraido para consulta. Em anexo segue xml de envio e o log completo da Bematech.

[anexos.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/2232315/anexos.zip)

25/07/2018|18:16:59|SAT-AC|info|Iniciando recebimento de dados de venda...
25/07/2018|18:16:59|AC-SAT|info|Iniciando execução do comando EnviarDadosVenda
25/07/2018|18:00:12|SAT-AC|info|447626|06010|1999|Erro desconhecido||
25/07/2018|18:00:12|AC-SAT|erro|Erro ao realizar a validação dos parâmetros
25/07/2018|18:00:12|AC-SAT|erro|Erro ao receber os dados de venda
25/07/2018|18:00:12|AC-SAT|info|Erro ao validar dados de venda com o xsd
25/07/2018|18:00:12|AC-SAT|info|Erro de validação com o xsd: Element 'xNome': This element is not expected. Expected is ( IE ). 
25/07/2018|18:00:12|AC-SAT|info|Erro de validação com o xsd: Element 'infCFe', attribute 'versao': The attribute 'versao' is not allowed. 

Desde de já agradeço, Obrigado.

**Comment by marcosgerene** [comment]
Se você informa o xNome do destinatário precisa informar o CPF. Se não tem destinatário (no caso está vendendo pra consumidor) não informe nada, nem o xNome

**Comment by eduferrari32** [comment]
Fiz este teste ainda continua com mesmo erro, a impressão que da é que o problema é na tag xNome do Emitente...

**Comment by eduferrari32** [comment]
Boa tarde,
So para informar que consegui resolver o problema. Eu estava passando varias informações que não precisa, no caso do emitente bastava passar IE, CNPJ e IM por isso estava dando erro no Layout.
Em anexo estou enviando o xml no formato correto para envio ao SAT. Obrigado pelo apoio.

[AD20180726124554-584616-env.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/2232665/AD20180726124554-584616-env.zip)

**Comment by rftd** [comment]
Sim no Sat não precisa preencher todas as tag leia no Manual Sat quais tag você(AC) precisa preencher e quais tags o Sat que preenche e te retorna.
