### ISSUE TITLE
Utilizar em VS2015

### ISSUE THREAD

**Issue by WPita** [ACBrNet/ACBr.Net.Sat#80]
Baixei o arquivo e abri o projeto ACBr.Net.Sat.sln no VS2015 mas esta dando um erro em 
            this.acbrIntegrador = new ACBr.Net.Integrador.ACBrIntegrador(); 
Como posso solucionar isso.

**Comment by rftd** [comment]
Qual o erro ?
Recomendo utilizar o pacote do nuget.

**Comment by WPita** [comment]
Certo vou baixar o pacote no nuget, obrigado! O erro é que falta um pacote "Integrador" mas acho que baixando o pacote deve funcionar, valeu!

**Comment by rftd** [comment]
SIm se não estiver configurado para baixar automaticamente os pacotes ao compilar os mesmo precisam ser baixados anteriormente para funcionar corretamente.

**Comment by WPita** [comment]
É um complicometro a mais eu não manjo de c# e para falar a verdade o mundo .net entrei a pouco tempo, mas vou lutando aqui, obrigado!

**Comment by WPita** [comment]
Só para constar, esta dando erro quando tento abrir o form.


  | Instances of this error (1)         1.   ACBr.Net.Sat.Demo FrmMain.Designer.cs Line:1354  Column:1   

            this.acbrSat.Encoding = ((System.Text.Encoding)(resources.GetObject("acbrSat.Encoding")));
            this.acbrSat.IntegradorFiscal = this.acbrIntegrador;
            this.acbrSat.Modelo = ACBr.Net.Sat.ModeloSat.Cdecl;
            this.acbrSat.PathDll = "C:\\SAT\\SAT.dll";
            this.acbrSat.SignAC = "";

**Comment by rftd** [comment]
enviei uma possível correção atualize seu repositório e tente novamente.

**Comment by WPita** [comment]
RFTD obrigado pela sua paciência mas ainda nada!

![image](https://user-images.githubusercontent.com/40769809/45168198-172e6d80-b1d1-11e8-93bf-8d7e0c961c02.png)

**Comment by rftd** [comment]
Isto parece ser recurso de linguagem não disponível no VS2015, pq não utiliza o [VS2017 ](https://visualstudio.microsoft.com/pt-br/downloads/?rr=https%3A%2F%2Fwww.google.com.br%2F)Community é gratuito.

**Comment by WPita** [comment]
Ok, Obrigado! Vou atualizar a versão!
