### ISSUE TITLE
Venda Cartão - NSU ou Código de Autorização errado

### ISSUE THREAD

**Issue by lukaz-sampaio** [ACBrNet/ACBr.Net.Sat#81]
No cenário em que o cliente não tem acesso à internet no momento, quando uma venda é feita no cartão e o cliente não validou o código POS junto a SEFAZ (no caso do CE, pode usar o http://simuladorposceara.azurewebsites.net/Index) a SEFAZ orienta que o usuário digite os dados manualmente e depois envie a venda. A dúvida é se tem como validar os códigos NSU/Código de Autorização no caso de o usuário digitar um dos dois códigos ou os dois errados. Lembrando que o código NSU não é o da SEFAZ e sim do cartão.

**Comment by rftd** [comment]
Eu não conheço nenhum algorítimo par validar NSU do cartão.

**Comment by lukaz-sampaio** [comment]
Realmente não é possível validar o código NSU.
