### ISSUE TITLE
Erro na função PreencheNItem

### ISSUE THREAD

**Issue by leandrovip** [ACBrNet/ACBr.Net.Sat#86]
Estou utilizando a função **PreencheNItem** mas ela não funcionou como esperado. Adicionei três itens e todos vieram com _NItem = 0_.

Notei que na atribuição do valor _NItem_ a variavel _i_ do vetor é alterada:

`det.NItem = i++;`

Fiz um teste e alterando da forma abaixo resolveu o problema

`det.NItem = i + 1;`

[]´s

**Comment by rftd** [comment]
A função esta errada, mas ai é por causa que eu fiz cagada mesmo kkkkkkkkk.
Fiz ela pensando em foreach e coloquei dentro de um for.

**Comment by leandrovip** [comment]
Foi o que eu imaginei heheh! 

Obrigado!

[]´s
