### ISSUE TITLE
Componente de Impressão não definido

### ISSUE THREAD

**Issue by valentimmx** [ACBrNet/ACBr.Net.Sat#87]
Olá, estou tendo problemas ao imprimir o extrato via S@T Demo, me retorna a exceção "Componente de Impressão não definido".
Oque faço nesse caso? Sou novato no uso deste componente.
Grato desde já.

**Comment by leandrovip** [comment]
Não fiz testes de impressão pelo Demo, mas conforme o **Readme** ele utiliza o _FastReports_ (pago) para tal.

> Os projetos de impressão do Extrato usa o FastReport e esta em https://github.com/ACBrNet/ACBr.Net.Sat.Extrato.FastReport
Uma versão demo do FastReport pode ser baixada em https://www.fast-report.com/pt/product/fast-report-net/

Chegou a instalar?
