### ISSUE TITLE
Impressão FastReports TANCA TP-450

### ISSUE THREAD

**Issue by mvtaraujo** [ACBrNet/ACBr.Net.Sat#88]
Ola pessoal, estou com um problema que não consigo descobrir o que é.
No código abaixo eu consigo imprimir na Bematech normalmente (única que testei até agora). No cliente tem uma TANCA TP-450, e esta não imprime por nada. Está funcionando normalmente pra outras impressões, somente o extrato do Sat que nao vai.

`ExtratoFastReport ExtratoFastReport = new ExtratoFastReport
                {
                    Impressora = "TP-450",//nome que ela está instalada no windows
                    LayOut = ExtratoLayOut.Completo,
                    NumeroCopias = 1
                };
                ExtratoFastReport.ImprimirExtrato(CFe.Load(sat.XMLFinal));//XML em string`

Mais se eu colocar **ExtratoFastReport.MostrarSetup = true;** mando imprimir pelo setup, a impressão sai normal.

Já fiz teste com o app demo e acontece o mesmo.

Alguém já teve este problema ou algo parecido?

**Comment by thiagojandrade** [comment]
Ac

**Comment by leandrovip** [comment]
Não sei se tem relação, mas, a impressora está instalada com driver genérico? E a da bematech?

**Comment by mvtaraujo** [comment]
> Não sei se tem relação, mas, a impressora está instalada com driver genérico? E a da bematech?

@leandrovip ambas estão instaladas com drivers próprios no windows, nenhuma generic

**Comment by mvtaraujo** [comment]
Consegui descobrir, o erro foi meu aqui. A impressora estava com nome fixado nas configurações..
