### ISSUE TITLE
Exemplo teste

### ISSUE THREAD

**Issue by dkraide** [ACBrNet/ACBr.Net.Sat#89]
Olá, tenho algumas curiosidades, ficaria muito feliz se me ajudassem, pois sou novato :)

 Estudando o projeto exemplo, na função "GerarDFE" é preenchido os campos dos produtos e do consumidor, mas não preenche os campos do Emitente. Na função também não ficou claro pra mim como coloco no xml a assinatura e o cnpj da software house. Como funciona essa parte ?

**Comment by rftd** [comment]
Se você notar no demo tem as configurações sobre emitente, quando preenche o mesmo preenche os campos do componente.

**Comment by marcosgerene** [comment]
@dkraide dentro do infCFe existe o atributo Emit que seria para informar o emitente, mas o seu preenchimento não é necessário pois ao preencher o objeto ACBrSAT e usar o método "NewCFe();" o mesmo já vem preenchido.

![image](https://user-images.githubusercontent.com/15945003/57943641-e8fa4500-78aa-11e9-99ea-021989a65101.png)


exemplo do meu código de preenchimento:
![image](https://user-images.githubusercontent.com/15945003/57943687-08916d80-78ab-11e9-8624-3e96ac8a4e6e.png)

**Comment by dkraide** [comment]
Muito obrigado pelos esclarecimentos!
