### ISSUE TITLE
Erro ao adicionar valor de desconto

### ISSUE THREAD

**Issue by dkraide** [ACBrNet/ACBr.Net.Sat#91]
Olá, estou com problemas ao adicionar Desconto no valor total do pedido...

Estou tentando na seguinte linha de codigo :
if(venda.valorDesconto > 0)
            {
                cfeAtual.InfCFe.Total.DescAcrEntr.VDescSubtot = Decimal.Parse(venda.valorDesconto.ToString());

            }

porem o sat esta me retornando os erros:

[2019-07-12 15:52:47.711]:Erro no Campo 'vCFe' : Campo vCFe maior que a soma dos valores do MP.
[2019-07-12 15:52:47.717]:ERRO NA EMISSAO: 1408: null

Teria como me ajudar? por favor :(

Quanto tento sem desconto vai normal

**Comment by PauloGama95** [comment]
Olá, a  coleção de pagamentos (InfCFe.Pagto.Pagamentos)   o valor da soma dos pagamentos inseridos confere com o valor total do cupom, ja com desconto aplicado?,

se você conseguir postar o xml de envio gerado para melhor lhe ajudar

**Comment by marcosgerene** [comment]
@dkraide o total dos descontos não devem ser preenchido. O sat calcula isso automaticamente somando os itens e devolve no xmls do CFe emitido.

https://github.com/ACBrNet/ACBr.Net.Sat/issues/68
https://github.com/ACBrNet/ACBr.Net.Sat/issues/30
