### ISSUE TITLE
Erro na validação do qrcode

### ISSUE THREAD

**Issue by mvtaraujo** [ACBrNet/ACBr.Net.Sat#92]
Olá pessoal. Quando leio o qrcode no app de olho na nota, da esse erro:

![51372A73-0387-42DD-A155-63EA5DB4602B](https://user-images.githubusercontent.com/2230616/62810098-44675800-bad3-11e9-8092-3d1a890269a5.png)

O valor do CFe do QRcode não é valido.
O cupom está autorizado e no site consigo consultar com a chave sem problemas.

Sabem o que pode ser?

**Comment by rftd** [comment]
rapaz isso nunca aconteceu comigo não, o valor dos dados do QrCode é retornado pelo próprio aparelho senão to enganado, mas da para gerar os mesmo dados

**Comment by PauloGama95** [comment]
Olá mvtaraujo comigo que eu me recorde ocorreu porem so validando o cupom gerado pelo emulador, caso voce possui algum aparelho sat ou cliente que ja emite o cupom  em produção teste o qrcode gerado pelo aparelho , caso contrario o problema pode estar no seu relatório do cupom fiscal quando gera o qrcode, talvez não esta recebendo os parâmetros conforme o manual de orientação 
https://portal.fazenda.sp.gov.br/servicos/sat/Downloads/Manual_Orientacao_SAT_v_MO_2_12_11.pdf
