### ISSUE TITLE
SAT Não funcionando em Modo produção.

### ISSUE THREAD

**Issue by dkraide** [ACBrNet/ACBr.Net.Sat#93]
Pessoal, to com muita dificuldade em por o acbrSAT pra funcionar no modo Produção.. no emulador funciona tudo ok, ja em Producao no cliente o sistema simplesmente FECHA sem aparecer erro nenhum!

 Criadores, há alguma forma de eu contratar o suporte de vocês?

**Comment by PauloGama95** [comment]
Olá eu utilizo o acbr sat em meu sistema, no inicio tive o mesmo problema o meu problema estava relacionado na inicializacao da DLL eu estava inicializando ela a cada emissão de cupom, modifiquei para inicializar ela somente na abertura do sistema e meu problema foi resolvido, verifique se voce nao esta fazendo a mesma coisa pode ser isso.

Verifique tambem se voce esta utilizando a DLL compativel com o aparelho (Cdecl ou StdCall).

**Comment by rftd** [comment]
Erro muito comum também é colocar o modelo com cdecl sendo que geralmente as dll dos sat dos fabricantes no windows são stdcall diferente do emulador.

**Comment by dkraide** [comment]
Realmente eu estava fazendo esses dois erros kk.. Amanhã eu irei visitar o cliente para testar, infelizmente ele não tem disponibilidade hoje. Muito obrigado pessoal !
