### ISSUE TITLE
Erro ao compilar Solução

### ISSUE THREAD

**Issue by felipexpert** [ACBrNet/ACBr.Net.Sat#94]
Eu segui a instrução de setar o ACBr.Net.Sat.Demo como inicializador, e ele já vem com a dependencia do ACBr.Net.Sat, o ACBr.Net.Sat compila normalmente, mas quando tento complicar apenas o ACBr.Net.Sat.Demo ou a Solução inteira recebo o erro:

Assembly` "ACBr.Net.Sat" com identidade "ACBr.Net.Sat, Version=1.2.6.1, Culture=neutral, PublicKeyToken=d3bb9130f8b775a6" usa "ACBr.Net.Integrador, Version=1.2.0.0, Culture=neutral, PublicKeyToken=d3bb9130f8b775a6" que tem uma versão mais recente do que o assembly referenciado "ACBr.Net.Integrador" com identidade "ACBr.Net.Integrador, Version=1.0.3.0, Culture=neutral, `PublicKeyToken=d3bb9130f8b775a6"

**Comment by VHener** [comment]
Tive esse mesmo problema essa semana.
Para solucionar baixei o .Net Core 3.0 SDK, no link abaixo: 
https://dotnet.microsoft.com/download

Depois abri a solução, coloquei o ACBr.Net.Demo para inicializar, fui no gerenciador de Pacotes NuGet e atualizei todas as dependências.

Mandei compilar e foi.
