### ISSUE TITLE
SAT configuração Sweda

### ISSUE THREAD

**Issue by felipexpert** [ACBrNet/ACBr.Net.Sat#95]
SAT Sweda SS 1000 Funciona por rede, como configurá-lo

**Comment by marcosgerene** [comment]
@felipexpert 

Toda comunicação com o SAT, seja qual for a marca, é feita pela DLL fornecida pelo fabricante.

Toda DLL fornecida pelo fabricante deve implementar uma lista de comandos, atributos, etc (API).

Logo, a biblioteca desse repositório "só" vai chamar os comandos da DLL e passar os parâmetros para ela, toda parte de configuração para comunicação (porta COM/IP/etc) é de responsabilidade do fabricante, então, acredito que você deva consutlar a Sweda como deve ser feito essa configuração.

Se quiser um exemplo, a Bematech tem um ".ini", se não me engano chama Bemafi.ini, algo assim, aonde você coloca a porta ou diz para ele encontrar sozinho a porta, e a DLL trabalha através desse arquivo.

Acredito que a Sweda deve seguir uma linha parecida, logo, consulte o fabricante.

**Comment by marcosgerene** [comment]
Por favor, leia o manual (que por sinal, é um dos melhores que já vi entre as fabricantes): http://sistemas.sweda.com.br/downloads/SAT/Manual_Instalacao_SAT_SWEDA_v03.pdf


Se a aplicação fornecida pela Sweda conseguir efeturar um "Consulta SAT" com sucesso, esta biblioteca também conseguirá, já que, como disse anteriormente, toda comunicação é feita pela DLL.
