### ISSUE TITLE
Problemas com as novas versões do DFe.Core

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.Sat#97]
Boa tarde @rftd 

Com a atualização das dependencias o SAT não consegue deseralizar mais, da um erro para converter um int64 em um int32.

Testei com vários XMLs, um simples CFe.Load(xml) já estoura o problema, se quiser posto um xml de testes aqui.

**Comment by rftd** [comment]
Vou esta verificando o problema.
