### ISSUE TITLE
Problema em "Inicializar"

### ISSUE THREAD

**Issue by HimorriveL** [ACBrNet/ACBr.Net.Sat#98]
Pessoal, baixei a lib ACBrNet / ACBr.Net.Sat preenchi as informações da empresa e fiz um teste clicando em "Inicializar". O sitema apresentou o seguinte erro:

An unhandled exception of type 'ACBr.Net.Core.ACBrException' occurred in ACBr.Net.Core.dll
Additional information: Não foi possivel carregar a biblioteca.

No caso eu acessei o Nuget e consta lá ACBr.Net.Core, ACBr.Net.DFe.Core e também ACBr.Net.Integrador.

Sendo assim não deveria ter dado tudo certo? ou preciso fazer uma importação manual? se sim, onde baixo o arquivo?

**Comment by rftd** [comment]
Você precisar setar o local da dll do SAT e o tipo dela se é StdCall ou Cdecl, pois a comunicação com o aparelho é todo feito pela dll do fabricante ou da SEFAZ se estiver usando o emulador.

**Comment by HimorriveL** [comment]
eu ja setei o caminho do DLL SAT, já testei as 3 entrada e o erro persiste, a saber estou usando GERTEC

![image](https://user-images.githubusercontent.com/60895471/74184662-ece2aa00-4c25-11ea-9b27-78d296cfa567.png)

**Comment by rftd** [comment]
Conferiu se a versão da lib esta correta, lembrando que temos x64 e x86.
Conferiu se a dll do sat tem dependências e se os mesmo se encontram junto dela.
E a dll da Gertec usa Cdecl.

**Comment by HimorriveL** [comment]
a Gertec, usa somente uma DLL que está setada, referente ao x64 e x86 eu não mexi em nada, estou usando o projeto exemplo, no qual ja vem as lib no NUGET

**Comment by rftd** [comment]
Você não entendeu o projeto demo é em .net e esta configurado para AnyCPU ou seja a aplicação vai seguir o OS.
Você provavelmente esta usando um OS x64 ou seja seu programa é x64, então a dll que você vai usar também tem que ser x64 senão não será possível carregar a mesma e ocorrendo o erro acima mencionado.

**Comment by HimorriveL** [comment]
no caso, eu preciso remover o ACBr.Net.Core do Nuget e adicionar ele manual? ou só de eu adicionar deverá resolver o problema?

**Comment by rftd** [comment]
não amigo to precisa usar uma dll da Gertec que seja x64.

**Comment by marcosgerene** [comment]
@HimorriveL 

O que o @rftd  está falando é sobre a arquitetura, mas acredito que o demo já esteja como x86.

Faz um teste, altera o demo para x86, aqui:

![image](https://user-images.githubusercontent.com/15945003/74205325-a3aa4e80-4c55-11ea-8084-817fd1143c7f.png)

PS: A sua aplicação provavelmente terá que ser alterada para x86 para funcionar também, infelizmente um número considerável de fabricante só fornecem dlls x86.

----

Agora quanto ao erro "não é possível carregar a biblioteca", acredito que seja um bug do demo que "não atualiza" algumas informações. Então, após alterar algo (tipo o caminho da Dll) clica em "Gravar" e logo em seguinda em "Ler" para que exista um "refresh forçado".

Feito isto basta inicializar normalmente.

**Comment by HimorriveL** [comment]
entendi, fiz a alteração pra x86 e coloquei como Cdecl, e o erro persiste, da uma olhada:
![image](https://user-images.githubusercontent.com/60895471/74254401-2b806f00-4ccf-11ea-9d4f-db200c503d35.png)

![image](https://user-images.githubusercontent.com/60895471/74254462-3b984e80-4ccf-11ea-91a3-999ab9ef2d62.png)

![image](https://user-images.githubusercontent.com/60895471/74254515-4f43b500-4ccf-11ea-8827-c5cd3fbb1552.png)

**Comment by leandrovip** [comment]
Usa o modelo **stdcall**

**Comment by HimorriveL** [comment]
An unhandled exception of type 'ACBr.Net.Core.ACBrException' occurred in ACBr.Net.Core.dll
Additional information: Não foi possivel carregar a biblioteca.

mesmo erro

**Comment by HimorriveL** [comment]
pessoal, eu setei dentro do sistema o caminho, para nao setar toda hora, agora quando eu clico no campo apago uma ele e adiciono novamente, ele funciona corretamente, obg a todos
