### ISSUE TITLE
SAT OFFLINE + ACBr.Net.Sat-master

### ISSUE THREAD

**Issue by HimorriveL** [ACBrNet/ACBr.Net.Sat#99]
Fiz o teste com os arquivos disponibilizado pelo emulador_off_line_v2_9_4pela SEFAZ

SAT Ativado

o Aplicativo Comercial está emitindo cupom fiscal.

Preenchi as informações no ACBr.Net.Sat-master e estou recebendo a seguinte informação no Monitor SAT:

[2020-02-14 15:38:25.369]:Campo 'CNPJ' invalido
[2020-02-14 15:38:25.374]:Erro no campo 'dest'
[2020-02-14 15:38:25.379]:ERRO NA EMISSAO: 1235: null

na ocasião deveria ter funcionado?

 

Segue XML que está sendo gerado pelo ACBr.Net.Sat-master 

[teste_XML.txt](https://github.com/ACBrNet/ACBr.Net.Sat/files/4206315/teste_XML.txt)

coloquei em TXT porque não suporta XML

**Comment by marcosgerene** [comment]
@HimorriveL 
Eu tenho o emissor instalado aqui e consigo usar normalmente, segue pasta do emulador e xml de exemplo:

[teste.zip](https://github.com/ACBrNet/ACBr.Net.Sat/files/4207450/teste.zip)

**Comment by marcosgerene** [comment]
Dentro do zip:
Emulador (o que está aqui em C:\Program Files (x86)\SAT-CFe\Emulador\)
Sat (o que está em c:\sat\)

e um xml de exemplo aqui

**Comment by HimorriveL** [comment]
obrigado pelo retorno!
Acredito que o problema possa estar no App exemplo já que ele está gerando tags vazia peguei o começo do xml gerado, dá uma olhada, ele está gerando tags vazia:

![image](https://user-images.githubusercontent.com/60895471/74669580-32ebc080-5186-11ea-9b8f-25d28ffd8390.png)

mesmo sem preencher nada de dest ele gera

![image](https://user-images.githubusercontent.com/60895471/74669608-472fbd80-5186-11ea-8969-a2ac3c448412.png)

**Comment by marcosgerene** [comment]
@HimorriveL 

Sobre o app teste estar gerando tags vazias, provavelmente "você não preencheu, mesmo tendo preenchido" os valores... rs

Se não me engano tem um bugzinho no demo... faz um teste, preenche os dados, clica em "Gravar" e depois em "Ler" e tenta enviar o xml de novo, veja se o problema é resolvido

**Comment by HimorriveL** [comment]
eu fiz um teste, eu criei uma nova classe, e preenchi o cfeAtual somente com alguns dados, e mesmo assim ele está gerando com os campos vazios, mesmo sem eu ter setado em lugar algum.

**Comment by marcosgerene** [comment]
@HimorriveL 
Tem campos que são obrigatórios, então ele gera mesmo não tendo valor, isso é natural.

Ex: mod, nCFe, etc... mesmo que vc não preencha a tag será gerada visto que o campo é obrigatório

**Comment by HimorriveL** [comment]
tudo bem, concordo, o problema por exemplo é ele estar gerando o DEST mesmo NÃO SENDO OBRIGATORIO e mesmo ele não tendo preenchimento algum, é ai que estou tentando entender, o porque disso, se a lib está com algum problema, ou se eu estou fazendo algo errado, mesmo não setando as informações, ele estar gerando. EDIT: já tentei tambem setar o DEST como NULL, como new CFeDest() e mesmo assim não está resolvendo o problema

**Comment by rftd** [comment]
realmente esta com um bug na classe de serializador, já estou corrigindo.
